<?xml version="1.0" encoding="utf-8"?>
<Database Name="textmetal_sample" EntityNamespace="TextMetal.HostImpl.AspNetSample.DomainModel.L2S" ContextNamespace="TextMetal.HostImpl.AspNetSample.DomainModel.L2S" Class="TextMetalOdsDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="global.EmailAttachment" Member="Global_EmailAttachments">
    <Type Name="Global_EmailAttachment">
      <Column Name="EmailAttachmentId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="true" />
      <Column Name="EmailMessageId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="true" />
      <Column Name="FileName" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="true" />
      <Column Name="FileSize" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="true" />
      <Column Name="MimeType" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="true" />
      <Column Name="AttachmentBits" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="SortOrder" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="CreationTimestamp" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="true" />
      <Column Name="ModificationTimestamp" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="true" />
      <Column Name="CreationUserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModificationUserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LogicalDelete" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="true" />
      <Association Name="fk_EmailAttachment_EmailMessage" Member="Global_EmailMessage" ThisKey="EmailMessageId" OtherKey="EmailMessageId" Type="Global_EmailMessage" IsForeignKey="true" />
      <Association Name="fk_EmailAttachment_User_creation" Member="Global_User" ThisKey="CreationUserId" OtherKey="UserId" Type="Global_User" IsForeignKey="true" />
      <Association Name="fk_EmailAttachment_User_modification" Member="ModificationUser" ThisKey="ModificationUserId" OtherKey="UserId" Type="Global_User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="history.EmailAttachmentHistory" Member="History_EmailAttachmentHistories">
    <Type Name="History_EmailAttachmentHistory">
      <Column Name="EmailAttachmentHistoryId" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="true" />
      <Column Name="EmailAttachmentHistoryTs" Type="System.DateTime" DbType="DateTime2(7) NOT NULL" CanBeNull="true" />
      <Column Name="EmailMessageId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="true" />
      <Column Name="EmailAttachmentId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FileName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="FileSize" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="MimeType" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="AttachmentBits" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="SortOrder" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="CreationTimestamp" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModificationTimestamp" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreationUserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModificationUserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LogicalDelete" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="global.EmailMessage" Member="Global_EmailMessages">
    <Type Name="Global_EmailMessage">
      <Column Name="EmailMessageId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="true" />
      <Column Name="From" Type="System.String" DbType="NVarChar(2047) NOT NULL" CanBeNull="true" />
      <Column Name="Sender" Type="System.String" DbType="NVarChar(2047)" CanBeNull="true" />
      <Column Name="ReplyTo" Type="System.String" DbType="NVarChar(2047)" CanBeNull="true" />
      <Column Name="To" Type="System.String" DbType="NVarChar(2047) NOT NULL" CanBeNull="true" />
      <Column Name="CarbonCopy" Type="System.String" DbType="NVarChar(2047)" CanBeNull="true" />
      <Column Name="BlindCarbonCopy" Type="System.String" DbType="NVarChar(2047)" CanBeNull="true" />
      <Column Name="Subject" Type="System.String" DbType="NVarChar(2047) NOT NULL" CanBeNull="true" />
      <Column Name="IsBodyHtml" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="true" />
      <Column Name="Body" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Processed" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="true" />
      <Column Name="SortOrder" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="CreationTimestamp" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="true" />
      <Column Name="ModificationTimestamp" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="true" />
      <Column Name="CreationUserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModificationUserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LogicalDelete" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="true" />
      <Association Name="fk_EmailAttachment_EmailMessage" Member="Global_EmailAttachment" ThisKey="EmailMessageId" OtherKey="EmailMessageId" Type="Global_EmailAttachment" Cardinality="One" DeleteRule="NO ACTION" />
      <Association Name="fk_EmailMessage_User_creation" Member="Global_User" ThisKey="CreationUserId" OtherKey="UserId" Type="Global_User" IsForeignKey="true" />
      <Association Name="fk_EmailMessage_User_modification" Member="ModificationUser" ThisKey="ModificationUserId" OtherKey="UserId" Type="Global_User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="history.EmailMessageHistory" Member="History_EmailMessageHistories">
    <Type Name="History_EmailMessageHistory">
      <Column Name="EmailMessageHistoryId" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="true" />
      <Column Name="EmailMessageHistoryTs" Type="System.DateTime" DbType="DateTime2(7) NOT NULL" CanBeNull="true" />
      <Column Name="EmailMessageId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="true" />
      <Column Name="From" Type="System.String" DbType="NVarChar(2047)" CanBeNull="true" />
      <Column Name="Sender" Type="System.String" DbType="NVarChar(2047)" CanBeNull="true" />
      <Column Name="ReplyTo" Type="System.String" DbType="NVarChar(2047)" CanBeNull="true" />
      <Column Name="To" Type="System.String" DbType="NVarChar(2047)" CanBeNull="true" />
      <Column Name="CarbonCopy" Type="System.String" DbType="NVarChar(2047)" CanBeNull="true" />
      <Column Name="BlindCarbonCopy" Type="System.String" DbType="NVarChar(2047)" CanBeNull="true" />
      <Column Name="Subject" Type="System.String" DbType="NVarChar(2047)" CanBeNull="true" />
      <Column Name="IsBodyHtml" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Body" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Processed" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="SortOrder" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="CreationTimestamp" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModificationTimestamp" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreationUserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModificationUserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LogicalDelete" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="global.EventLog" Member="Global_EventLogs">
    <Type Name="Global_EventLog">
      <Column Name="EventLogId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="true" />
      <Column Name="EventText" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="SortOrder" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="CreationTimestamp" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="true" />
      <Column Name="ModificationTimestamp" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="true" />
      <Column Name="CreationUserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModificationUserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LogicalDelete" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="true" />
      <Association Name="fk_EventLog_User_creation" Member="Global_User" ThisKey="CreationUserId" OtherKey="UserId" Type="Global_User" IsForeignKey="true" />
      <Association Name="fk_EventLog_User_modification" Member="ModificationUser" ThisKey="ModificationUserId" OtherKey="UserId" Type="Global_User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.EventLogExtent" Member="EventLogExtents">
    <Type Name="EventLogExtent">
      <Column Name="MinCreationTimestamp" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="AvgDifferenceTimestamps" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaxModificationTimestamp" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="history.EventLogHistory" Member="History_EventLogHistories">
    <Type Name="History_EventLogHistory">
      <Column Name="EventLogHistoryId" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="true" />
      <Column Name="EventLogHistoryTs" Type="System.DateTime" DbType="DateTime2(7) NOT NULL" CanBeNull="true" />
      <Column Name="EventLogId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="true" />
      <Column Name="EventText" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="SortOrder" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="CreationTimestamp" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModificationTimestamp" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreationUserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModificationUserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LogicalDelete" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="application.Member" Member="Application_Members">
    <Type Name="Application_Member">
      <Column Name="MemberId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="true" />
      <Column Name="OrganizationId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="true" />
      <Column Name="ParentMemberId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MemberName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="MemberTitle" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="SecurityRoleId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="true" />
      <Column Name="SortOrder" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="CreationTimestamp" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="true" />
      <Column Name="ModificationTimestamp" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="true" />
      <Column Name="CreationUserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="true" />
      <Column Name="ModificationUserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="true" />
      <Column Name="LogicalDelete" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="true" />
      <Association Name="fk_Member_Member_parent" Member="ParentMember" ThisKey="ParentMemberId" OtherKey="MemberId" Type="Application_Member" IsForeignKey="true" />
      <Association Name="fk_Member_Member_parent" Member="Members" ThisKey="MemberId" OtherKey="ParentMemberId" Type="Application_Member" DeleteRule="NO ACTION" />
      <Association Name="fk_Member_Organization" Member="Application_Organization" ThisKey="OrganizationId" OtherKey="OrganizationId" Type="Application_Organization" IsForeignKey="true" />
      <Association Name="fk_Member_SecurityRole" Member="Global_SecurityRole" ThisKey="SecurityRoleId" OtherKey="SecurityRoleId" Type="Global_SecurityRole" IsForeignKey="true" />
      <Association Name="fk_Member_User" Member="Global_User" ThisKey="MemberId" OtherKey="UserId" Type="Global_User" IsForeignKey="true" />
      <Association Name="fk_Member_User_creation" Member="CreationUser" ThisKey="CreationUserId" OtherKey="UserId" Type="Global_User" IsForeignKey="true" />
      <Association Name="fk_Member_User_modification" Member="ModificationUser" ThisKey="ModificationUserId" OtherKey="UserId" Type="Global_User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="history.MemberHistory" Member="History_MemberHistories">
    <Type Name="History_MemberHistory">
      <Column Name="MemberHistoryId" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="true" />
      <Column Name="MemberHistoryTs" Type="System.DateTime" DbType="DateTime2(7) NOT NULL" CanBeNull="true" />
      <Column Name="MemberId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="true" />
      <Column Name="OrganizationId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ParentMemberId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MemberName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="MemberTitle" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="SecurityRoleId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SortOrder" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="CreationTimestamp" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModificationTimestamp" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreationUserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModificationUserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LogicalDelete" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="application.Organization" Member="Application_Organizations">
    <Type Name="Application_Organization">
      <Column Name="OrganizationId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="true" />
      <Column Name="ParentOrganizationId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OrganizationName" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="true" />
      <Column Name="TimeZoneId" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="SortOrder" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="CreationTimestamp" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="true" />
      <Column Name="ModificationTimestamp" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="true" />
      <Column Name="CreationUserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="true" />
      <Column Name="ModificationUserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="true" />
      <Column Name="LogicalDelete" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="true" />
      <Association Name="fk_Member_Organization" Member="Application_Members" ThisKey="OrganizationId" OtherKey="OrganizationId" Type="Application_Member" DeleteRule="NO ACTION" />
      <Association Name="fk_Organization_Organization_parent" Member="ParentOrganization" ThisKey="ParentOrganizationId" OtherKey="OrganizationId" Type="Application_Organization" IsForeignKey="true" />
      <Association Name="fk_Organization_Organization_parent" Member="Organizations" ThisKey="OrganizationId" OtherKey="ParentOrganizationId" Type="Application_Organization" DeleteRule="NO ACTION" />
      <Association Name="fk_Organization_User_creation" Member="Global_User" ThisKey="CreationUserId" OtherKey="UserId" Type="Global_User" IsForeignKey="true" />
      <Association Name="fk_Organization_User_modification" Member="ModificationUser" ThisKey="ModificationUserId" OtherKey="UserId" Type="Global_User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="history.OrganizationHistory" Member="History_OrganizationHistories">
    <Type Name="History_OrganizationHistory">
      <Column Name="OrganizationHistoryId" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="true" />
      <Column Name="OrganizationHistoryTs" Type="System.DateTime" DbType="DateTime2(7) NOT NULL" CanBeNull="true" />
      <Column Name="OrganizationId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="true" />
      <Column Name="ParentOrganizationId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OrganizationName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="TimeZoneId" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="SortOrder" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="CreationTimestamp" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModificationTimestamp" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreationUserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModificationUserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LogicalDelete" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="global.PropertyBag" Member="Global_PropertyBags">
    <Type Name="Global_PropertyBag">
      <Column Name="PropertyBagId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="true" />
      <Column Name="PropertyKey" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="true" />
      <Column Name="PropertyType" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="PropertyValue" Type="System.String" DbType="NVarChar(2047)" CanBeNull="true" />
      <Column Name="SortOrder" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="CreationTimestamp" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="true" />
      <Column Name="ModificationTimestamp" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="true" />
      <Column Name="CreationUserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="true" />
      <Column Name="ModificationUserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="true" />
      <Column Name="LogicalDelete" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="true" />
      <Association Name="fk_PropertyBag_User_creation" Member="Global_User" ThisKey="CreationUserId" OtherKey="UserId" Type="Global_User" IsForeignKey="true" />
      <Association Name="fk_PropertyBag_User_modification" Member="ModificationUser" ThisKey="ModificationUserId" OtherKey="UserId" Type="Global_User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="history.PropertyBagHistory" Member="History_PropertyBagHistories">
    <Type Name="History_PropertyBagHistory">
      <Column Name="PropertyBagHistoryId" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="true" />
      <Column Name="PropertyBagHistoryTs" Type="System.DateTime" DbType="DateTime2(7) NOT NULL" CanBeNull="true" />
      <Column Name="PropertyBagId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="true" />
      <Column Name="PropertyKey" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="PropertyType" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="PropertyValue" Type="System.String" DbType="NVarChar(2047)" CanBeNull="true" />
      <Column Name="SortOrder" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="CreationTimestamp" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModificationTimestamp" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreationUserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModificationUserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LogicalDelete" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="global.SecurityRole" Member="Global_SecurityRoles">
    <Type Name="Global_SecurityRole">
      <Column Name="SecurityRoleId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="true" />
      <Column Name="SecurityRoleName" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="true" />
      <Column Name="SortOrder" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="CreationTimestamp" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="true" />
      <Column Name="ModificationTimestamp" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="true" />
      <Column Name="CreationUserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="true" />
      <Column Name="ModificationUserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="true" />
      <Column Name="LogicalDelete" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="true" />
      <Association Name="fk_Member_SecurityRole" Member="Application_Members" ThisKey="SecurityRoleId" OtherKey="SecurityRoleId" Type="Application_Member" DeleteRule="NO ACTION" />
      <Association Name="fk_SecurityRole_User_creation" Member="Global_User" ThisKey="CreationUserId" OtherKey="UserId" Type="Global_User" IsForeignKey="true" />
      <Association Name="fk_SecurityRole_User_modification" Member="ModificationUser" ThisKey="ModificationUserId" OtherKey="UserId" Type="Global_User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="history.SecurityRoleHistory" Member="History_SecurityRoleHistories">
    <Type Name="History_SecurityRoleHistory">
      <Column Name="SecurityRoleHistoryId" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="true" />
      <Column Name="SecurityRoleHistoryTs" Type="System.DateTime" DbType="DateTime2(7) NOT NULL" CanBeNull="true" />
      <Column Name="SecurityRoleId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="true" />
      <Column Name="SecurityRoleName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="SortOrder" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="CreationTimestamp" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModificationTimestamp" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreationUserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModificationUserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LogicalDelete" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="testcases.tab_no_primary_key_no_identity" Member="Testcases_Tab_no_primary_key_no_identities">
    <Type Name="Testcases_Tab_no_primary_key_no_identity">
      <Column Name="col_bigint" Member="Col_bigint" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="col_binary" Member="Col_binary" Type="System.Data.Linq.Binary" DbType="Binary(1)" CanBeNull="true" />
      <Column Name="col_bit" Member="Col_bit" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="col_char" Member="Col_char" Type="System.String" DbType="Char(1)" CanBeNull="true" />
      <Column Name="col_date" Member="Col_date" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="col_datetime" Member="Col_datetime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="col_datetime2" Member="Col_datetime2" Type="System.DateTime" DbType="DateTime2(7)" CanBeNull="true" />
      <Column Name="col_datetimeoffset" Member="Col_datetimeoffset" Type="System.DateTimeOffset" DbType="DateTimeOffset(7)" CanBeNull="true" />
      <Column Name="col_decimal" Member="Col_decimal" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="col_float" Member="Col_float" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="col_image" Member="Col_image" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" />
      <Column Name="col_int" Member="Col_int" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="col_money" Member="Col_money" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="col_nchar" Member="Col_nchar" Type="System.String" DbType="NChar(1)" CanBeNull="true" />
      <Column Name="col_ntext" Member="Col_ntext" Type="System.String" DbType="NText" CanBeNull="true" />
      <Column Name="col_numeric" Member="Col_numeric" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="col_nvarchar" Member="Col_nvarchar" Type="System.String" DbType="NVarChar(1)" CanBeNull="true" />
      <Column Name="col_real" Member="Col_real" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="col_rowversion" Member="Col_rowversion" Type="System.Data.Linq.Binary" DbType="rowversion" CanBeNull="true" IsVersion="true" />
      <Column Name="col_smalldatetime" Member="Col_smalldatetime" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="col_smallint" Member="Col_smallint" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="col_smallmoney" Member="Col_smallmoney" Type="System.Decimal" DbType="SmallMoney" CanBeNull="true" />
      <Column Name="col_sql_variant" Member="Col_sql_variant" Type="System.Object" DbType="sql_variant" CanBeNull="true" />
      <Column Name="col_sysname" Member="Col_sysname" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="col_text" Member="Col_text" Type="System.String" DbType="Text" CanBeNull="true" />
      <Column Name="col_time" Member="Col_time" Type="System.TimeSpan" DbType="Time(7)" CanBeNull="true" />
      <Column Name="col_tinyint" Member="Col_tinyint" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="col_uniqueidentifier" Member="Col_uniqueidentifier" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="col_varbinary" Member="Col_varbinary" Type="System.Data.Linq.Binary" DbType="VarBinary(1)" CanBeNull="true" />
      <Column Name="col_varchar" Member="Col_varchar" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="col_xml" Member="Col_xml" Type="System.Xml.Linq.XElement" DbType="Xml" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="testcases.tab_with_composite_primary_key_no_identity" Member="Testcases_Tab_with_composite_primary_key_no_identities">
    <Type Name="Testcases_Tab_with_composite_primary_key_no_identity">
      <Column Name="col_int_pk0" Member="Col_int_pk0" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="true" />
      <Column Name="col_int_pk1" Member="Col_int_pk1" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="true" />
      <Column Name="col_int_pk2" Member="Col_int_pk2" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="true" />
      <Column Name="col_int_pk3" Member="Col_int_pk3" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="true" />
      <Column Name="col_bigint" Member="Col_bigint" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="col_binary" Member="Col_binary" Type="System.Data.Linq.Binary" DbType="Binary(1)" CanBeNull="true" />
      <Column Name="col_bit" Member="Col_bit" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="col_char" Member="Col_char" Type="System.String" DbType="Char(1)" CanBeNull="true" />
      <Column Name="col_date" Member="Col_date" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="col_datetime" Member="Col_datetime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="col_datetime2" Member="Col_datetime2" Type="System.DateTime" DbType="DateTime2(7)" CanBeNull="true" />
      <Column Name="col_datetimeoffset" Member="Col_datetimeoffset" Type="System.DateTimeOffset" DbType="DateTimeOffset(7)" CanBeNull="true" />
      <Column Name="col_decimal" Member="Col_decimal" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="col_float" Member="Col_float" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="col_image" Member="Col_image" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" />
      <Column Name="col_int" Member="Col_int" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="col_money" Member="Col_money" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="col_nchar" Member="Col_nchar" Type="System.String" DbType="NChar(1)" CanBeNull="true" />
      <Column Name="col_ntext" Member="Col_ntext" Type="System.String" DbType="NText" CanBeNull="true" />
      <Column Name="col_numeric" Member="Col_numeric" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="col_nvarchar" Member="Col_nvarchar" Type="System.String" DbType="NVarChar(1)" CanBeNull="true" />
      <Column Name="col_real" Member="Col_real" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="col_rowversion" Member="Col_rowversion" Type="System.Data.Linq.Binary" DbType="rowversion" CanBeNull="true" IsVersion="true" />
      <Column Name="col_smalldatetime" Member="Col_smalldatetime" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="col_smallint" Member="Col_smallint" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="col_smallmoney" Member="Col_smallmoney" Type="System.Decimal" DbType="SmallMoney" CanBeNull="true" />
      <Column Name="col_sql_variant" Member="Col_sql_variant" Type="System.Object" DbType="sql_variant" CanBeNull="true" />
      <Column Name="col_sysname" Member="Col_sysname" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="col_text" Member="Col_text" Type="System.String" DbType="Text" CanBeNull="true" />
      <Column Name="col_time" Member="Col_time" Type="System.TimeSpan" DbType="Time(7)" CanBeNull="true" />
      <Column Name="col_tinyint" Member="Col_tinyint" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="col_uniqueidentifier" Member="Col_uniqueidentifier" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="col_varbinary" Member="Col_varbinary" Type="System.Data.Linq.Binary" DbType="VarBinary(1)" CanBeNull="true" />
      <Column Name="col_varchar" Member="Col_varchar" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="col_xml" Member="Col_xml" Type="System.Xml.Linq.XElement" DbType="Xml" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="testcases.tab_with_no_primary_key_with_identity" Member="Testcases_Tab_with_no_primary_key_with_identities">
    <Type Name="Testcases_Tab_with_no_primary_key_with_identity">
      <Column Name="col_int_id" Member="Col_int_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="true" />
      <Column Name="col_bigint" Member="Col_bigint" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="col_binary" Member="Col_binary" Type="System.Data.Linq.Binary" DbType="Binary(1)" CanBeNull="true" />
      <Column Name="col_bit" Member="Col_bit" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="col_char" Member="Col_char" Type="System.String" DbType="Char(1)" CanBeNull="true" />
      <Column Name="col_date" Member="Col_date" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="col_datetime" Member="Col_datetime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="col_datetime2" Member="Col_datetime2" Type="System.DateTime" DbType="DateTime2(7)" CanBeNull="true" />
      <Column Name="col_datetimeoffset" Member="Col_datetimeoffset" Type="System.DateTimeOffset" DbType="DateTimeOffset(7)" CanBeNull="true" />
      <Column Name="col_decimal" Member="Col_decimal" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="col_float" Member="Col_float" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="col_image" Member="Col_image" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" />
      <Column Name="col_int" Member="Col_int" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="col_money" Member="Col_money" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="col_nchar" Member="Col_nchar" Type="System.String" DbType="NChar(1)" CanBeNull="true" />
      <Column Name="col_ntext" Member="Col_ntext" Type="System.String" DbType="NText" CanBeNull="true" />
      <Column Name="col_numeric" Member="Col_numeric" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="col_nvarchar" Member="Col_nvarchar" Type="System.String" DbType="NVarChar(1)" CanBeNull="true" />
      <Column Name="col_real" Member="Col_real" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="col_rowversion" Member="Col_rowversion" Type="System.Data.Linq.Binary" DbType="rowversion" CanBeNull="true" IsVersion="true" />
      <Column Name="col_smalldatetime" Member="Col_smalldatetime" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="col_smallint" Member="Col_smallint" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="col_smallmoney" Member="Col_smallmoney" Type="System.Decimal" DbType="SmallMoney" CanBeNull="true" />
      <Column Name="col_sql_variant" Member="Col_sql_variant" Type="System.Object" DbType="sql_variant" CanBeNull="true" />
      <Column Name="col_sysname" Member="Col_sysname" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="col_text" Member="Col_text" Type="System.String" DbType="Text" CanBeNull="true" />
      <Column Name="col_time" Member="Col_time" Type="System.TimeSpan" DbType="Time(7)" CanBeNull="true" />
      <Column Name="col_tinyint" Member="Col_tinyint" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="col_uniqueidentifier" Member="Col_uniqueidentifier" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="col_varbinary" Member="Col_varbinary" Type="System.Data.Linq.Binary" DbType="VarBinary(1)" CanBeNull="true" />
      <Column Name="col_varchar" Member="Col_varchar" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="col_xml" Member="Col_xml" Type="System.Xml.Linq.XElement" DbType="Xml" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="testcases.tab_with_primary_key_as_default" Member="Testcases_Tab_with_primary_key_as_defaults">
    <Type Name="Testcases_Tab_with_primary_key_as_default">
      <Column Name="col_uuid_df_pk" Member="Col_uuid_df_pk" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="true" />
      <Column Name="col_bigint" Member="Col_bigint" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="col_binary" Member="Col_binary" Type="System.Data.Linq.Binary" DbType="Binary(1)" CanBeNull="true" />
      <Column Name="col_bit" Member="Col_bit" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="col_char" Member="Col_char" Type="System.String" DbType="Char(1)" CanBeNull="true" />
      <Column Name="col_date" Member="Col_date" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="col_datetime" Member="Col_datetime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="col_datetime2" Member="Col_datetime2" Type="System.DateTime" DbType="DateTime2(7)" CanBeNull="true" />
      <Column Name="col_datetimeoffset" Member="Col_datetimeoffset" Type="System.DateTimeOffset" DbType="DateTimeOffset(7)" CanBeNull="true" />
      <Column Name="col_decimal" Member="Col_decimal" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="col_float" Member="Col_float" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="col_image" Member="Col_image" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" />
      <Column Name="col_int" Member="Col_int" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="col_money" Member="Col_money" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="col_nchar" Member="Col_nchar" Type="System.String" DbType="NChar(1)" CanBeNull="true" />
      <Column Name="col_ntext" Member="Col_ntext" Type="System.String" DbType="NText" CanBeNull="true" />
      <Column Name="col_numeric" Member="Col_numeric" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="col_nvarchar" Member="Col_nvarchar" Type="System.String" DbType="NVarChar(1)" CanBeNull="true" />
      <Column Name="col_real" Member="Col_real" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="col_rowversion" Member="Col_rowversion" Type="System.Data.Linq.Binary" DbType="rowversion" CanBeNull="true" IsVersion="true" />
      <Column Name="col_smalldatetime" Member="Col_smalldatetime" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="col_smallint" Member="Col_smallint" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="col_smallmoney" Member="Col_smallmoney" Type="System.Decimal" DbType="SmallMoney" CanBeNull="true" />
      <Column Name="col_sql_variant" Member="Col_sql_variant" Type="System.Object" DbType="sql_variant" CanBeNull="true" />
      <Column Name="col_sysname" Member="Col_sysname" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="col_text" Member="Col_text" Type="System.String" DbType="Text" CanBeNull="true" />
      <Column Name="col_time" Member="Col_time" Type="System.TimeSpan" DbType="Time(7)" CanBeNull="true" />
      <Column Name="col_tinyint" Member="Col_tinyint" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="col_uniqueidentifier" Member="Col_uniqueidentifier" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="col_varbinary" Member="Col_varbinary" Type="System.Data.Linq.Binary" DbType="VarBinary(1)" CanBeNull="true" />
      <Column Name="col_varchar" Member="Col_varchar" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="col_xml" Member="Col_xml" Type="System.Xml.Linq.XElement" DbType="Xml" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="testcases.tab_with_primary_key_as_identity" Member="Testcases_Tab_with_primary_key_as_identities">
    <Type Name="Testcases_Tab_with_primary_key_as_identity">
      <Column Name="col_int_id_pk" Member="Col_int_id_pk" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="true" />
      <Column Name="col_bigint" Member="Col_bigint" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="col_binary" Member="Col_binary" Type="System.Data.Linq.Binary" DbType="Binary(1)" CanBeNull="true" />
      <Column Name="col_bit" Member="Col_bit" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="col_char" Member="Col_char" Type="System.String" DbType="Char(1)" CanBeNull="true" />
      <Column Name="col_date" Member="Col_date" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="col_datetime" Member="Col_datetime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="col_datetime2" Member="Col_datetime2" Type="System.DateTime" DbType="DateTime2(7)" CanBeNull="true" />
      <Column Name="col_datetimeoffset" Member="Col_datetimeoffset" Type="System.DateTimeOffset" DbType="DateTimeOffset(7)" CanBeNull="true" />
      <Column Name="col_decimal" Member="Col_decimal" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="col_float" Member="Col_float" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="col_image" Member="Col_image" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" />
      <Column Name="col_int" Member="Col_int" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="col_money" Member="Col_money" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="col_nchar" Member="Col_nchar" Type="System.String" DbType="NChar(1)" CanBeNull="true" />
      <Column Name="col_ntext" Member="Col_ntext" Type="System.String" DbType="NText" CanBeNull="true" />
      <Column Name="col_numeric" Member="Col_numeric" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="col_nvarchar" Member="Col_nvarchar" Type="System.String" DbType="NVarChar(1)" CanBeNull="true" />
      <Column Name="col_real" Member="Col_real" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="col_rowversion" Member="Col_rowversion" Type="System.Data.Linq.Binary" DbType="rowversion" CanBeNull="true" IsVersion="true" />
      <Column Name="col_smalldatetime" Member="Col_smalldatetime" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="col_smallint" Member="Col_smallint" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="col_smallmoney" Member="Col_smallmoney" Type="System.Decimal" DbType="SmallMoney" CanBeNull="true" />
      <Column Name="col_sql_variant" Member="Col_sql_variant" Type="System.Object" DbType="sql_variant" CanBeNull="true" />
      <Column Name="col_sysname" Member="Col_sysname" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="col_text" Member="Col_text" Type="System.String" DbType="Text" CanBeNull="true" />
      <Column Name="col_time" Member="Col_time" Type="System.TimeSpan" DbType="Time(7)" CanBeNull="true" />
      <Column Name="col_tinyint" Member="Col_tinyint" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="col_uniqueidentifier" Member="Col_uniqueidentifier" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="col_varbinary" Member="Col_varbinary" Type="System.Data.Linq.Binary" DbType="VarBinary(1)" CanBeNull="true" />
      <Column Name="col_varchar" Member="Col_varchar" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="col_xml" Member="Col_xml" Type="System.Xml.Linq.XElement" DbType="Xml" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="testcases.tab_with_primary_key_no_identity" Member="Testcases_Tab_with_primary_key_no_identities">
    <Type Name="Testcases_Tab_with_primary_key_no_identity">
      <Column Name="col_int_pk" Member="Col_int_pk" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="true" />
      <Column Name="col_bigint" Member="Col_bigint" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="col_binary" Member="Col_binary" Type="System.Data.Linq.Binary" DbType="Binary(1)" CanBeNull="true" />
      <Column Name="col_bit" Member="Col_bit" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="col_char" Member="Col_char" Type="System.String" DbType="Char(1)" CanBeNull="true" />
      <Column Name="col_date" Member="Col_date" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="col_datetime" Member="Col_datetime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="col_datetime2" Member="Col_datetime2" Type="System.DateTime" DbType="DateTime2(7)" CanBeNull="true" />
      <Column Name="col_datetimeoffset" Member="Col_datetimeoffset" Type="System.DateTimeOffset" DbType="DateTimeOffset(7)" CanBeNull="true" />
      <Column Name="col_decimal" Member="Col_decimal" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="col_float" Member="Col_float" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="col_image" Member="Col_image" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" />
      <Column Name="col_int" Member="Col_int" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="col_money" Member="Col_money" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="col_nchar" Member="Col_nchar" Type="System.String" DbType="NChar(1)" CanBeNull="true" />
      <Column Name="col_ntext" Member="Col_ntext" Type="System.String" DbType="NText" CanBeNull="true" />
      <Column Name="col_numeric" Member="Col_numeric" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="col_nvarchar" Member="Col_nvarchar" Type="System.String" DbType="NVarChar(1)" CanBeNull="true" />
      <Column Name="col_real" Member="Col_real" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="col_rowversion" Member="Col_rowversion" Type="System.Data.Linq.Binary" DbType="rowversion" CanBeNull="true" IsVersion="true" />
      <Column Name="col_smalldatetime" Member="Col_smalldatetime" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="col_smallint" Member="Col_smallint" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="col_smallmoney" Member="Col_smallmoney" Type="System.Decimal" DbType="SmallMoney" CanBeNull="true" />
      <Column Name="col_sql_variant" Member="Col_sql_variant" Type="System.Object" DbType="sql_variant" CanBeNull="true" />
      <Column Name="col_sysname" Member="Col_sysname" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="col_text" Member="Col_text" Type="System.String" DbType="Text" CanBeNull="true" />
      <Column Name="col_time" Member="Col_time" Type="System.TimeSpan" DbType="Time(7)" CanBeNull="true" />
      <Column Name="col_tinyint" Member="Col_tinyint" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="col_uniqueidentifier" Member="Col_uniqueidentifier" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="col_varbinary" Member="Col_varbinary" Type="System.Data.Linq.Binary" DbType="VarBinary(1)" CanBeNull="true" />
      <Column Name="col_varchar" Member="Col_varchar" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="col_xml" Member="Col_xml" Type="System.Xml.Linq.XElement" DbType="Xml" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="testcases.tab_with_primary_key_with_different_identity" Member="Testcases_Tab_with_primary_key_with_different_identities">
    <Type Name="Testcases_Tab_with_primary_key_with_different_identity">
      <Column Name="col_int_pk" Member="Col_int_pk" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="true" />
      <Column Name="col_int_id" Member="Col_int_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="true" />
      <Column Name="col_bigint" Member="Col_bigint" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="col_binary" Member="Col_binary" Type="System.Data.Linq.Binary" DbType="Binary(1)" CanBeNull="true" />
      <Column Name="col_bit" Member="Col_bit" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="col_char" Member="Col_char" Type="System.String" DbType="Char(1)" CanBeNull="true" />
      <Column Name="col_date" Member="Col_date" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="col_datetime" Member="Col_datetime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="col_datetime2" Member="Col_datetime2" Type="System.DateTime" DbType="DateTime2(7)" CanBeNull="true" />
      <Column Name="col_datetimeoffset" Member="Col_datetimeoffset" Type="System.DateTimeOffset" DbType="DateTimeOffset(7)" CanBeNull="true" />
      <Column Name="col_decimal" Member="Col_decimal" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="col_float" Member="Col_float" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="col_image" Member="Col_image" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" />
      <Column Name="col_int" Member="Col_int" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="col_money" Member="Col_money" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="col_nchar" Member="Col_nchar" Type="System.String" DbType="NChar(1)" CanBeNull="true" />
      <Column Name="col_ntext" Member="Col_ntext" Type="System.String" DbType="NText" CanBeNull="true" />
      <Column Name="col_numeric" Member="Col_numeric" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="col_nvarchar" Member="Col_nvarchar" Type="System.String" DbType="NVarChar(1)" CanBeNull="true" />
      <Column Name="col_real" Member="Col_real" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="col_rowversion" Member="Col_rowversion" Type="System.Data.Linq.Binary" DbType="rowversion" CanBeNull="true" IsVersion="true" />
      <Column Name="col_smalldatetime" Member="Col_smalldatetime" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="col_smallint" Member="Col_smallint" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="col_smallmoney" Member="Col_smallmoney" Type="System.Decimal" DbType="SmallMoney" CanBeNull="true" />
      <Column Name="col_sql_variant" Member="Col_sql_variant" Type="System.Object" DbType="sql_variant" CanBeNull="true" />
      <Column Name="col_sysname" Member="Col_sysname" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="col_text" Member="Col_text" Type="System.String" DbType="Text" CanBeNull="true" />
      <Column Name="col_time" Member="Col_time" Type="System.TimeSpan" DbType="Time(7)" CanBeNull="true" />
      <Column Name="col_tinyint" Member="Col_tinyint" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="col_uniqueidentifier" Member="Col_uniqueidentifier" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="col_varbinary" Member="Col_varbinary" Type="System.Data.Linq.Binary" DbType="VarBinary(1)" CanBeNull="true" />
      <Column Name="col_varchar" Member="Col_varchar" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="col_xml" Member="Col_xml" Type="System.Xml.Linq.XElement" DbType="Xml" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="global.User" Member="Global_Users">
    <Type Name="Global_User">
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="true" />
      <Column Name="EmailAddress" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="true" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="true" />
      <Column Name="SaltValue" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="true" />
      <Column Name="PasswordHash" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="true" />
      <Column Name="Question" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="true" />
      <Column Name="AnswerHash" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="true" />
      <Column Name="LastLoginSuccessTimestamp" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LastLoginFailureTimestamp" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FailedLoginCount" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="true" />
      <Column Name="MustChangePassword" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="true" />
      <Column Name="SortOrder" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="CreationTimestamp" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="true" />
      <Column Name="ModificationTimestamp" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="true" />
      <Column Name="CreationUserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="true" />
      <Column Name="ModificationUserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="true" />
      <Column Name="LogicalDelete" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="true" />
      <Association Name="fk_Member_User" Member="Application_Member" ThisKey="UserId" OtherKey="MemberId" Type="Application_Member" Cardinality="One" DeleteRule="NO ACTION" />
      <Association Name="fk_Member_User_creation" Member="Application_Members" ThisKey="UserId" OtherKey="CreationUserId" Type="Application_Member" DeleteRule="NO ACTION" />
      <Association Name="fk_Member_User_modification" Member="Users" ThisKey="UserId" OtherKey="ModificationUserId" Type="Application_Member" DeleteRule="NO ACTION" />
      <Association Name="fk_Organization_User_creation" Member="Application_Organizations" ThisKey="UserId" OtherKey="CreationUserId" Type="Application_Organization" DeleteRule="NO ACTION" />
      <Association Name="fk_Organization_User_modification" Member="Organization_User_modifications" ThisKey="UserId" OtherKey="ModificationUserId" Type="Application_Organization" DeleteRule="NO ACTION" />
      <Association Name="fk_EmailAttachment_User_creation" Member="Global_EmailAttachments" ThisKey="UserId" OtherKey="CreationUserId" Type="Global_EmailAttachment" DeleteRule="NO ACTION" />
      <Association Name="fk_EmailAttachment_User_modification" Member="EmailAttachment_User_modifications" ThisKey="UserId" OtherKey="ModificationUserId" Type="Global_EmailAttachment" DeleteRule="NO ACTION" />
      <Association Name="fk_EmailMessage_User_creation" Member="Global_EmailMessages" ThisKey="UserId" OtherKey="CreationUserId" Type="Global_EmailMessage" DeleteRule="NO ACTION" />
      <Association Name="fk_EmailMessage_User_modification" Member="EmailMessage_User_modifications" ThisKey="UserId" OtherKey="ModificationUserId" Type="Global_EmailMessage" DeleteRule="NO ACTION" />
      <Association Name="fk_EventLog_User_creation" Member="Global_EventLogs" ThisKey="UserId" OtherKey="CreationUserId" Type="Global_EventLog" DeleteRule="NO ACTION" />
      <Association Name="fk_EventLog_User_modification" Member="EventLog_User_modifications" ThisKey="UserId" OtherKey="ModificationUserId" Type="Global_EventLog" DeleteRule="NO ACTION" />
      <Association Name="fk_PropertyBag_User_creation" Member="Global_PropertyBags" ThisKey="UserId" OtherKey="CreationUserId" Type="Global_PropertyBag" DeleteRule="NO ACTION" />
      <Association Name="fk_PropertyBag_User_modification" Member="PropertyBag_User_modifications" ThisKey="UserId" OtherKey="ModificationUserId" Type="Global_PropertyBag" DeleteRule="NO ACTION" />
      <Association Name="fk_SecurityRole_User_creation" Member="Global_SecurityRoles" ThisKey="UserId" OtherKey="CreationUserId" Type="Global_SecurityRole" DeleteRule="NO ACTION" />
      <Association Name="fk_SecurityRole_User_modification" Member="SecurityRole_User_modifications" ThisKey="UserId" OtherKey="ModificationUserId" Type="Global_SecurityRole" DeleteRule="NO ACTION" />
      <Association Name="fk_User_User_creation" Member="CreationUser" ThisKey="CreationUserId" OtherKey="UserId" Type="Global_User" IsForeignKey="true" />
      <Association Name="fk_User_User_creation" Member="User_User_creations" ThisKey="UserId" OtherKey="CreationUserId" Type="Global_User" DeleteRule="NO ACTION" />
      <Association Name="fk_User_User_modification" Member="ModificationUser" ThisKey="ModificationUserId" OtherKey="UserId" Type="Global_User" IsForeignKey="true" />
      <Association Name="fk_User_User_modification" Member="User_User_modifications" ThisKey="UserId" OtherKey="ModificationUserId" Type="Global_User" DeleteRule="NO ACTION" />
    </Type>
  </Table>
  <Table Name="history.UserHistory" Member="History_UserHistories">
    <Type Name="History_UserHistory">
      <Column Name="UserHistoryId" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="true" />
      <Column Name="UserHistoryTs" Type="System.DateTime" DbType="DateTime2(7) NOT NULL" CanBeNull="true" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="true" />
      <Column Name="EmailAddress" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="SaltValue" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="PasswordHash" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Question" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="AnswerHash" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="LastLoginSuccessTimestamp" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LastLoginFailureTimestamp" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FailedLoginCount" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="MustChangePassword" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="SortOrder" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="CreationTimestamp" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModificationTimestamp" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreationUserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModificationUserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LogicalDelete" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="testcases.sproc_simple" Method="Testcases_Sproc_simple">
    <Parameter Name="num" Type="System.Int32" DbType="Int" />
    <Parameter Name="den" Type="System.Int32" DbType="Int" />
    <Parameter Name="res" Type="System.Double" DbType="Float" Direction="InOut" />
    <Return Type="System.Int32" DbType="Int" />
  </Function>
</Database>