//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by:
// TextMetal 6.0.0.37114;
// 		Copyright ©2002-2014 Daniel Bullington (dpbullington@gmail.com)
//		Distributed under the MIT license: http://www.opensource.org/licenses/mit-license.php
//		Project URL: https://github.com/dpbullington/textmetal
//
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//
// </auto-generated>
//------------------------------------------------------------------------------

/*
	Copyright ©2002-2014 Daniel Bullington (dpbullington@gmail.com)
	Distributed under the MIT license: http://www.opensource.org/licenses/mit-license.php
*/

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Xml;

using TextMetal.Common.Core;
using TextMetal.Common.Data;
using TextMetal.Common.Data.Framework;
using TextMetal.Common.Syntax.Expressions;
using TextMetal.Common.Syntax.Operators;
using TextMetal.Common.Syntax.Statements;

namespace TextMetal.HostImpl.AspNetSample.DomainModel.Tables
{
	public partial class EmailAttachmentHistory : Object, INotifyPropertyChanged, IEmailAttachmentHistory
	{
		#region Constructors/Destructors

		public EmailAttachmentHistory()
		{
		}

		#endregion

		#region Fields/Constants

		public const string SCHEMA_NAME = "history";
		public const string TABLE_NAME = "EmailAttachmentHistory";
		public const bool HAS_SINGLE_COLUMN_SERVER_GENERATED_PRIMARY_KEY = true;
		public const string COLUMN_NAME_EMAIL_ATTACHMENT_HISTORY_ID = "EmailAttachmentHistoryId";
		public const string COLUMN_NAME_EMAIL_ATTACHMENT_HISTORY_TS = "EmailAttachmentHistoryTs";
		public const string COLUMN_NAME_EMAIL_MESSAGE_ID = "EmailMessageId";
		public const string COLUMN_NAME_EMAIL_ATTACHMENT_ID = "EmailAttachmentId";
		public const string COLUMN_NAME_FILE_NAME = "FileName";
		public const string COLUMN_NAME_FILE_SIZE = "FileSize";
		public const string COLUMN_NAME_MIME_TYPE = "MimeType";
		public const string COLUMN_NAME_ATTACHMENT_BITS = "AttachmentBits";
		public const string COLUMN_NAME_SORT_ORDER = "SortOrder";
		public const string COLUMN_NAME_CREATION_TIMESTAMP = "CreationTimestamp";
		public const string COLUMN_NAME_MODIFICATION_TIMESTAMP = "ModificationTimestamp";
		public const string COLUMN_NAME_CREATION_USER_ID = "CreationUserId";
		public const string COLUMN_NAME_MODIFICATION_USER_ID = "ModificationUserId";
		public const string COLUMN_NAME_LOGICAL_DELETE = "LogicalDelete";

		private Nullable<Int64> @emailAttachmentHistoryId;
		private Nullable<DateTime> @emailAttachmentHistoryTs;
		private Nullable<Int32> @emailMessageId;
		private Nullable<Int32> @emailAttachmentId;
		private String @fileName;
		private Nullable<Int64> @fileSize;
		private String @mimeType;
		private Byte[] @attachmentBits;
		private Nullable<Byte> @sortOrder;
		private Nullable<DateTime> @creationTimestamp;
		private Nullable<DateTime> @modificationTimestamp;
		private Nullable<Int32> @creationUserId;
		private Nullable<Int32> @modificationUserId;
		private Nullable<Boolean> @logicalDelete;

		#endregion

		#region Properties/Indexers/Events

		public event PropertyChangedEventHandler PropertyChanged;

		public virtual bool IsNew
		{
			get
			{
				return this.@EmailAttachmentHistoryId == default(Nullable<Int64>);
			}
			set
			{
				if(value)
					this.@EmailAttachmentHistoryId =  default(Nullable<Int64>);
			}
		}
		
		/* PRIMARY_KEY */
		public Nullable<Int64> @EmailAttachmentHistoryId
		{
			get
			{
				return this.@emailAttachmentHistoryId;
			}
			set
			{
				if (!DataType.ObjectsEqualValueSemantics(this.@emailAttachmentHistoryId, value))
				{
					this.@emailAttachmentHistoryId = value;
					OnPropertyChanged("EmailAttachmentHistoryId");
				}
			}
		}
		
		public Nullable<DateTime> @EmailAttachmentHistoryTs
		{
			get
			{
				return this.@emailAttachmentHistoryTs;
			}
			set
			{
				if (!DataType.ObjectsEqualValueSemantics(this.@emailAttachmentHistoryTs, value))
				{
					this.@emailAttachmentHistoryTs = value;
					OnPropertyChanged("EmailAttachmentHistoryTs");
				}
			}
		}
		
		public Nullable<Int32> @EmailMessageId
		{
			get
			{
				return this.@emailMessageId;
			}
			set
			{
				if (!DataType.ObjectsEqualValueSemantics(this.@emailMessageId, value))
				{
					this.@emailMessageId = value;
					OnPropertyChanged("EmailMessageId");
				}
			}
		}
		
		public Nullable<Int32> @EmailAttachmentId
		{
			get
			{
				return this.@emailAttachmentId;
			}
			set
			{
				if (!DataType.ObjectsEqualValueSemantics(this.@emailAttachmentId, value))
				{
					this.@emailAttachmentId = value;
					OnPropertyChanged("EmailAttachmentId");
				}
			}
		}
		
		public String @FileName
		{
			get
			{
				return this.@fileName;
			}
			set
			{
				if (!DataType.ObjectsEqualValueSemantics(this.@fileName, value))
				{
					this.@fileName = value;
					OnPropertyChanged("FileName");
				}
			}
		}
		
		public Nullable<Int64> @FileSize
		{
			get
			{
				return this.@fileSize;
			}
			set
			{
				if (!DataType.ObjectsEqualValueSemantics(this.@fileSize, value))
				{
					this.@fileSize = value;
					OnPropertyChanged("FileSize");
				}
			}
		}
		
		public String @MimeType
		{
			get
			{
				return this.@mimeType;
			}
			set
			{
				if (!DataType.ObjectsEqualValueSemantics(this.@mimeType, value))
				{
					this.@mimeType = value;
					OnPropertyChanged("MimeType");
				}
			}
		}
		
		public Byte[] @AttachmentBits
		{
			get
			{
				return this.@attachmentBits;
			}
			set
			{
				if (!DataType.ObjectsEqualValueSemantics(this.@attachmentBits, value))
				{
					this.@attachmentBits = value;
					OnPropertyChanged("AttachmentBits");
				}
			}
		}
		
		public Nullable<Byte> @SortOrder
		{
			get
			{
				return this.@sortOrder;
			}
			set
			{
				if (!DataType.ObjectsEqualValueSemantics(this.@sortOrder, value))
				{
					this.@sortOrder = value;
					OnPropertyChanged("SortOrder");
				}
			}
		}
		
		public Nullable<DateTime> @CreationTimestamp
		{
			get
			{
				return this.@creationTimestamp;
			}
			set
			{
				if (!DataType.ObjectsEqualValueSemantics(this.@creationTimestamp, value))
				{
					this.@creationTimestamp = value;
					OnPropertyChanged("CreationTimestamp");
				}
			}
		}
		
		public Nullable<DateTime> @ModificationTimestamp
		{
			get
			{
				return this.@modificationTimestamp;
			}
			set
			{
				if (!DataType.ObjectsEqualValueSemantics(this.@modificationTimestamp, value))
				{
					this.@modificationTimestamp = value;
					OnPropertyChanged("ModificationTimestamp");
				}
			}
		}
		
		public Nullable<Int32> @CreationUserId
		{
			get
			{
				return this.@creationUserId;
			}
			set
			{
				if (!DataType.ObjectsEqualValueSemantics(this.@creationUserId, value))
				{
					this.@creationUserId = value;
					OnPropertyChanged("CreationUserId");
				}
			}
		}
		
		public Nullable<Int32> @ModificationUserId
		{
			get
			{
				return this.@modificationUserId;
			}
			set
			{
				if (!DataType.ObjectsEqualValueSemantics(this.@modificationUserId, value))
				{
					this.@modificationUserId = value;
					OnPropertyChanged("ModificationUserId");
				}
			}
		}
		
		public Nullable<Boolean> @LogicalDelete
		{
			get
			{
				return this.@logicalDelete;
			}
			set
			{
				if (!DataType.ObjectsEqualValueSemantics(this.@logicalDelete, value))
				{
					this.@logicalDelete = value;
					OnPropertyChanged("LogicalDelete");
				}
			}
		}
		
		#endregion

		#region Methods/Operators

		partial void OnMark();

		partial void OnValidate(ref IEnumerable<Message> messages);

		public virtual void Mark()
		{
			this.OnMark();
		}

		public virtual IEnumerable<Message> Validate()
		{
			IEnumerable<Message> messages = null;

			this.OnValidate(ref messages);

			return messages ?? new Message[] { };
		}

		protected void OnAllPropertiesChanged()
        {
			this.OnPropertyChanged(null);
		}

		protected void OnPropertyChanged(string propertyName)
        {
			if ((object)this.PropertyChanged != null)
				PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
        }

		#endregion
	}
}
