//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by:
// TextMetal 6.0.0.37114;
// 		Copyright ©2002-2014 Daniel Bullington (dpbullington@gmail.com)
//		Distributed under the MIT license: http://www.opensource.org/licenses/mit-license.php
//		Project URL: https://github.com/dpbullington/textmetal
//
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//
// </auto-generated>
//------------------------------------------------------------------------------

/*
	Copyright ©2002-2014 Daniel Bullington (dpbullington@gmail.com)
	Distributed under the MIT license: http://www.opensource.org/licenses/mit-license.php
*/

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Xml;

using TextMetal.Common.Core;
using TextMetal.Common.Data;
using TextMetal.Common.Data.Framework;
using TextMetal.Common.Syntax.Expressions;
using TextMetal.Common.Syntax.Operators;
using TextMetal.Common.Syntax.Statements;

namespace TextMetal.HostImpl.AspNetSample.DomainModel.Tables
{
	public partial class MemberHistory : Object, INotifyPropertyChanged, IMemberHistory
	{
		#region Constructors/Destructors

		public MemberHistory()
		{
		}

		#endregion

		#region Fields/Constants

		public const string SCHEMA_NAME = "history";
		public const string TABLE_NAME = "MemberHistory";
		public const bool HAS_SINGLE_COLUMN_SERVER_GENERATED_PRIMARY_KEY = true;
		public const string COLUMN_NAME_MEMBER_HISTORY_ID = "MemberHistoryId";
		public const string COLUMN_NAME_MEMBER_HISTORY_TS = "MemberHistoryTs";
		public const string COLUMN_NAME_MEMBER_ID = "MemberId";
		public const string COLUMN_NAME_ORGANIZATION_ID = "OrganizationId";
		public const string COLUMN_NAME_PARENT_MEMBER_ID = "ParentMemberId";
		public const string COLUMN_NAME_MEMBER_NAME = "MemberName";
		public const string COLUMN_NAME_MEMBER_TITLE = "MemberTitle";
		public const string COLUMN_NAME_SECURITY_ROLE_ID = "SecurityRoleId";
		public const string COLUMN_NAME_SORT_ORDER = "SortOrder";
		public const string COLUMN_NAME_CREATION_TIMESTAMP = "CreationTimestamp";
		public const string COLUMN_NAME_MODIFICATION_TIMESTAMP = "ModificationTimestamp";
		public const string COLUMN_NAME_CREATION_USER_ID = "CreationUserId";
		public const string COLUMN_NAME_MODIFICATION_USER_ID = "ModificationUserId";
		public const string COLUMN_NAME_LOGICAL_DELETE = "LogicalDelete";

		private Nullable<Int64> @memberHistoryId;
		private Nullable<DateTime> @memberHistoryTs;
		private Nullable<Int32> @memberId;
		private Nullable<Int32> @organizationId;
		private Nullable<Int32> @parentMemberId;
		private String @memberName;
		private String @memberTitle;
		private Nullable<Int32> @securityRoleId;
		private Nullable<Byte> @sortOrder;
		private Nullable<DateTime> @creationTimestamp;
		private Nullable<DateTime> @modificationTimestamp;
		private Nullable<Int32> @creationUserId;
		private Nullable<Int32> @modificationUserId;
		private Nullable<Boolean> @logicalDelete;

		#endregion

		#region Properties/Indexers/Events

		public event PropertyChangedEventHandler PropertyChanged;

		public virtual bool IsNew
		{
			get
			{
				return this.@MemberHistoryId == default(Nullable<Int64>);
			}
			set
			{
				if(value)
					this.@MemberHistoryId =  default(Nullable<Int64>);
			}
		}
		
		/* PRIMARY_KEY */
		public Nullable<Int64> @MemberHistoryId
		{
			get
			{
				return this.@memberHistoryId;
			}
			set
			{
				if (!DataType.ObjectsEqualValueSemantics(this.@memberHistoryId, value))
				{
					this.@memberHistoryId = value;
					OnPropertyChanged("MemberHistoryId");
				}
			}
		}
		
		public Nullable<DateTime> @MemberHistoryTs
		{
			get
			{
				return this.@memberHistoryTs;
			}
			set
			{
				if (!DataType.ObjectsEqualValueSemantics(this.@memberHistoryTs, value))
				{
					this.@memberHistoryTs = value;
					OnPropertyChanged("MemberHistoryTs");
				}
			}
		}
		
		public Nullable<Int32> @MemberId
		{
			get
			{
				return this.@memberId;
			}
			set
			{
				if (!DataType.ObjectsEqualValueSemantics(this.@memberId, value))
				{
					this.@memberId = value;
					OnPropertyChanged("MemberId");
				}
			}
		}
		
		public Nullable<Int32> @OrganizationId
		{
			get
			{
				return this.@organizationId;
			}
			set
			{
				if (!DataType.ObjectsEqualValueSemantics(this.@organizationId, value))
				{
					this.@organizationId = value;
					OnPropertyChanged("OrganizationId");
				}
			}
		}
		
		public Nullable<Int32> @ParentMemberId
		{
			get
			{
				return this.@parentMemberId;
			}
			set
			{
				if (!DataType.ObjectsEqualValueSemantics(this.@parentMemberId, value))
				{
					this.@parentMemberId = value;
					OnPropertyChanged("ParentMemberId");
				}
			}
		}
		
		public String @MemberName
		{
			get
			{
				return this.@memberName;
			}
			set
			{
				if (!DataType.ObjectsEqualValueSemantics(this.@memberName, value))
				{
					this.@memberName = value;
					OnPropertyChanged("MemberName");
				}
			}
		}
		
		public String @MemberTitle
		{
			get
			{
				return this.@memberTitle;
			}
			set
			{
				if (!DataType.ObjectsEqualValueSemantics(this.@memberTitle, value))
				{
					this.@memberTitle = value;
					OnPropertyChanged("MemberTitle");
				}
			}
		}
		
		public Nullable<Int32> @SecurityRoleId
		{
			get
			{
				return this.@securityRoleId;
			}
			set
			{
				if (!DataType.ObjectsEqualValueSemantics(this.@securityRoleId, value))
				{
					this.@securityRoleId = value;
					OnPropertyChanged("SecurityRoleId");
				}
			}
		}
		
		public Nullable<Byte> @SortOrder
		{
			get
			{
				return this.@sortOrder;
			}
			set
			{
				if (!DataType.ObjectsEqualValueSemantics(this.@sortOrder, value))
				{
					this.@sortOrder = value;
					OnPropertyChanged("SortOrder");
				}
			}
		}
		
		public Nullable<DateTime> @CreationTimestamp
		{
			get
			{
				return this.@creationTimestamp;
			}
			set
			{
				if (!DataType.ObjectsEqualValueSemantics(this.@creationTimestamp, value))
				{
					this.@creationTimestamp = value;
					OnPropertyChanged("CreationTimestamp");
				}
			}
		}
		
		public Nullable<DateTime> @ModificationTimestamp
		{
			get
			{
				return this.@modificationTimestamp;
			}
			set
			{
				if (!DataType.ObjectsEqualValueSemantics(this.@modificationTimestamp, value))
				{
					this.@modificationTimestamp = value;
					OnPropertyChanged("ModificationTimestamp");
				}
			}
		}
		
		public Nullable<Int32> @CreationUserId
		{
			get
			{
				return this.@creationUserId;
			}
			set
			{
				if (!DataType.ObjectsEqualValueSemantics(this.@creationUserId, value))
				{
					this.@creationUserId = value;
					OnPropertyChanged("CreationUserId");
				}
			}
		}
		
		public Nullable<Int32> @ModificationUserId
		{
			get
			{
				return this.@modificationUserId;
			}
			set
			{
				if (!DataType.ObjectsEqualValueSemantics(this.@modificationUserId, value))
				{
					this.@modificationUserId = value;
					OnPropertyChanged("ModificationUserId");
				}
			}
		}
		
		public Nullable<Boolean> @LogicalDelete
		{
			get
			{
				return this.@logicalDelete;
			}
			set
			{
				if (!DataType.ObjectsEqualValueSemantics(this.@logicalDelete, value))
				{
					this.@logicalDelete = value;
					OnPropertyChanged("LogicalDelete");
				}
			}
		}
		
		#endregion

		#region Methods/Operators

		partial void OnMark();

		partial void OnValidate(ref IEnumerable<Message> messages);

		public virtual void Mark()
		{
			this.OnMark();
		}

		public virtual IEnumerable<Message> Validate()
		{
			IEnumerable<Message> messages = null;

			this.OnValidate(ref messages);

			return messages ?? new Message[] { };
		}

		protected void OnAllPropertiesChanged()
        {
			this.OnPropertyChanged(null);
		}

		protected void OnPropertyChanged(string propertyName)
        {
			if ((object)this.PropertyChanged != null)
				PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
        }

		#endregion
	}
}
