//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by:
// TextMetal 5.1.0.41861;
// 		Copyright ©2002-2014 Daniel Bullington (dpbullington@gmail.com)
//		Distributed under the MIT license: http://www.opensource.org/licenses/mit-license.php
//		Project URL: https://github.com/dpbullington/textmetal
//
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//
// </auto-generated>
//------------------------------------------------------------------------------

/*
	Copyright ©2002-2014 Daniel Bullington (dpbullington@gmail.com)
	Distributed under the MIT license: http://www.opensource.org/licenses/mit-license.php
*/

using System;
using System.Xml;

using TextMetal.Common.Core;

namespace TextMetal.HostImpl.AspNetSample.DomainModel.Tables
{
	public partial class MemberHistory : Object
	{		
		#region Constructors/Destructors
		
		public MemberHistory()
		{
		}
		
		#endregion
		
		#region Fields/Constants

		private Nullable<Int64> @memberHistoryId;
		private Nullable<DateTime> @memberHistoryTs;
		private Nullable<Int32> @memberId;
		private Nullable<Int32> @organizationId;
		private Nullable<Int32> @parentMemberId;
		private String @memberName;
		private String @memberTitle;
		private Nullable<Int32> @securityRoleId;
		private Nullable<Byte> @sortOrder;
		private Nullable<DateTime> @creationTimestamp;
		private Nullable<DateTime> @modificationTimestamp;
		private Nullable<Int32> @creationUserId;
		private Nullable<Int32> @modificationUserId;
		private Nullable<Boolean> @logicalDelete;

		#endregion

		#region Properties/Indexers/Events
		
		public virtual bool IsNew
		{
			get
			{
				return this.MemberHistoryId == default(Nullable<Int64>);
			}
			set
			{
				if(value)
					this.MemberHistoryId =  default(Nullable<Int64>);
			}
		}
		
		/* PRIMARY_KEY */
		public Nullable<Int64> @MemberHistoryId
		{
			get
			{
				return this.@memberHistoryId;
			}
			set
			{
				this.@memberHistoryId = value;
			}
		}
		
		public Nullable<DateTime> @MemberHistoryTs
		{
			get
			{
				return this.@memberHistoryTs;
			}
			set
			{
				this.@memberHistoryTs = value;
			}
		}
		
		public Nullable<Int32> @MemberId
		{
			get
			{
				return this.@memberId;
			}
			set
			{
				this.@memberId = value;
			}
		}
		
		public Nullable<Int32> @OrganizationId
		{
			get
			{
				return this.@organizationId;
			}
			set
			{
				this.@organizationId = value;
			}
		}
		
		public Nullable<Int32> @ParentMemberId
		{
			get
			{
				return this.@parentMemberId;
			}
			set
			{
				this.@parentMemberId = value;
			}
		}
		
		public String @MemberName
		{
			get
			{
				return this.@memberName;
			}
			set
			{
				this.@memberName = value;
			}
		}
		
		public String @MemberTitle
		{
			get
			{
				return this.@memberTitle;
			}
			set
			{
				this.@memberTitle = value;
			}
		}
		
		public Nullable<Int32> @SecurityRoleId
		{
			get
			{
				return this.@securityRoleId;
			}
			set
			{
				this.@securityRoleId = value;
			}
		}
		
		public Nullable<Byte> @SortOrder
		{
			get
			{
				return this.@sortOrder;
			}
			set
			{
				this.@sortOrder = value;
			}
		}
		
		public Nullable<DateTime> @CreationTimestamp
		{
			get
			{
				return this.@creationTimestamp;
			}
			set
			{
				this.@creationTimestamp = value;
			}
		}
		
		public Nullable<DateTime> @ModificationTimestamp
		{
			get
			{
				return this.@modificationTimestamp;
			}
			set
			{
				this.@modificationTimestamp = value;
			}
		}
		
		public Nullable<Int32> @CreationUserId
		{
			get
			{
				return this.@creationUserId;
			}
			set
			{
				this.@creationUserId = value;
			}
		}
		
		public Nullable<Int32> @ModificationUserId
		{
			get
			{
				return this.@modificationUserId;
			}
			set
			{
				this.@modificationUserId = value;
			}
		}
		
		public Nullable<Boolean> @LogicalDelete
		{
			get
			{
				return this.@logicalDelete;
			}
			set
			{
				this.@logicalDelete = value;
			}
		}
		
		#endregion
	}
}
