//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by:
// TextMetal 6.0.0.29228;
// 		Copyright ©2002-2014 Daniel Bullington (dpbullington@gmail.com)
//		Distributed under the MIT license: http://www.opensource.org/licenses/mit-license.php
//		Project URL: https://github.com/dpbullington/textmetal
//
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//
// </auto-generated>
//------------------------------------------------------------------------------

/*
	Copyright ©2002-2014 Daniel Bullington (dpbullington@gmail.com)
	Distributed under the MIT license: http://www.opensource.org/licenses/mit-license.php
*/

using System;
using System.Collections.Generic;
using System.Xml;

using TextMetal.Common.Core;
using TextMetal.Common.Data;
using TextMetal.Common.Data.Framework;
using TextMetal.Common.Expressions;

namespace TextMetal.HostImpl.AspNetSample.DomainModel.Tables
{
	public partial class OrganizationHistory : Object, IOrganizationHistory
	{		
		#region Constructors/Destructors
		
		public OrganizationHistory()
		{
		}
		
		#endregion
		
		#region Fields/Constants
		
		public const string SCHEMA_NAME = "history";
		public const string TABLE_NAME = "OrganizationHistory";
		public const bool HAS_SINGLE_COLUMN_SERVER_GENERATED_PRIMARY_KEY = true;
		public const string COLUMN_NAME_ORGANIZATION_HISTORY_ID = "OrganizationHistoryId";
		public const string COLUMN_NAME_ORGANIZATION_HISTORY_TS = "OrganizationHistoryTs";
		public const string COLUMN_NAME_ORGANIZATION_ID = "OrganizationId";
		public const string COLUMN_NAME_PARENT_ORGANIZATION_ID = "ParentOrganizationId";
		public const string COLUMN_NAME_ORGANIZATION_NAME = "OrganizationName";
		public const string COLUMN_NAME_TIME_ZONE_ID = "TimeZoneId";
		public const string COLUMN_NAME_SORT_ORDER = "SortOrder";
		public const string COLUMN_NAME_CREATION_TIMESTAMP = "CreationTimestamp";
		public const string COLUMN_NAME_MODIFICATION_TIMESTAMP = "ModificationTimestamp";
		public const string COLUMN_NAME_CREATION_USER_ID = "CreationUserId";
		public const string COLUMN_NAME_MODIFICATION_USER_ID = "ModificationUserId";
		public const string COLUMN_NAME_LOGICAL_DELETE = "LogicalDelete";

		private Nullable<Int64> @organizationHistoryId;
		private Nullable<DateTime> @organizationHistoryTs;
		private Nullable<Int32> @organizationId;
		private Nullable<Int32> @parentOrganizationId;
		private String @organizationName;
		private String @timeZoneId;
		private Nullable<Byte> @sortOrder;
		private Nullable<DateTime> @creationTimestamp;
		private Nullable<DateTime> @modificationTimestamp;
		private Nullable<Int32> @creationUserId;
		private Nullable<Int32> @modificationUserId;
		private Nullable<Boolean> @logicalDelete;

		#endregion

		#region Properties/Indexers/Events
		
		public virtual bool IsNew
		{
			get
			{
				return this.@OrganizationHistoryId == default(Nullable<Int64>);
			}
			set
			{
				if(value)
					this.@OrganizationHistoryId =  default(Nullable<Int64>);
			}
		}
		
		/* PRIMARY_KEY */
		public Nullable<Int64> @OrganizationHistoryId
		{
			get
			{
				return this.@organizationHistoryId;
			}
			set
			{
				this.@organizationHistoryId = value;
			}
		}
		
		public Nullable<DateTime> @OrganizationHistoryTs
		{
			get
			{
				return this.@organizationHistoryTs;
			}
			set
			{
				this.@organizationHistoryTs = value;
			}
		}
		
		public Nullable<Int32> @OrganizationId
		{
			get
			{
				return this.@organizationId;
			}
			set
			{
				this.@organizationId = value;
			}
		}
		
		public Nullable<Int32> @ParentOrganizationId
		{
			get
			{
				return this.@parentOrganizationId;
			}
			set
			{
				this.@parentOrganizationId = value;
			}
		}
		
		public String @OrganizationName
		{
			get
			{
				return this.@organizationName;
			}
			set
			{
				this.@organizationName = value;
			}
		}
		
		public String @TimeZoneId
		{
			get
			{
				return this.@timeZoneId;
			}
			set
			{
				this.@timeZoneId = value;
			}
		}
		
		public Nullable<Byte> @SortOrder
		{
			get
			{
				return this.@sortOrder;
			}
			set
			{
				this.@sortOrder = value;
			}
		}
		
		public Nullable<DateTime> @CreationTimestamp
		{
			get
			{
				return this.@creationTimestamp;
			}
			set
			{
				this.@creationTimestamp = value;
			}
		}
		
		public Nullable<DateTime> @ModificationTimestamp
		{
			get
			{
				return this.@modificationTimestamp;
			}
			set
			{
				this.@modificationTimestamp = value;
			}
		}
		
		public Nullable<Int32> @CreationUserId
		{
			get
			{
				return this.@creationUserId;
			}
			set
			{
				this.@creationUserId = value;
			}
		}
		
		public Nullable<Int32> @ModificationUserId
		{
			get
			{
				return this.@modificationUserId;
			}
			set
			{
				this.@modificationUserId = value;
			}
		}
		
		public Nullable<Boolean> @LogicalDelete
		{
			get
			{
				return this.@logicalDelete;
			}
			set
			{
				this.@logicalDelete = value;
			}
		}
		
		#endregion
		
		#region Methods/Operators
		
		partial void OnMark();
		
		partial void OnValidate(ref IEnumerable<Message> messages);
		
		public virtual void Mark()
		{
			this.OnMark();
		}
		
		public virtual IEnumerable<Message> Validate()
		{
			IEnumerable<Message> messages = null;
			
			this.OnValidate(ref messages);
			
			return messages ?? new Message[] { };
		}
		
		#endregion
	}
}
