//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by:
// TextMetal 5.1.0.41861;
// 		Copyright ©2002-2014 Daniel Bullington (dpbullington@gmail.com)
//		Distributed under the MIT license: http://www.opensource.org/licenses/mit-license.php
//		Project URL: https://github.com/dpbullington/textmetal
//
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//
// </auto-generated>
//------------------------------------------------------------------------------

/*
	Copyright ©2002-2014 Daniel Bullington (dpbullington@gmail.com)
	Distributed under the MIT license: http://www.opensource.org/licenses/mit-license.php
*/

using System;
using System.Xml;

using TextMetal.Common.Core;

namespace TextMetal.HostImpl.AspNetSample.DomainModel.Tables
{
	public partial class SecurityRoleHistory : Object
	{		
		#region Constructors/Destructors
		
		public SecurityRoleHistory()
		{
		}
		
		#endregion
		
		#region Fields/Constants

		private Nullable<Int64> @securityRoleHistoryId;
		private Nullable<DateTime> @securityRoleHistoryTs;
		private Nullable<Int32> @securityRoleId;
		private String @securityRoleName;
		private Nullable<Byte> @sortOrder;
		private Nullable<DateTime> @creationTimestamp;
		private Nullable<DateTime> @modificationTimestamp;
		private Nullable<Int32> @creationUserId;
		private Nullable<Int32> @modificationUserId;
		private Nullable<Boolean> @logicalDelete;

		#endregion

		#region Properties/Indexers/Events
		
		public virtual bool IsNew
		{
			get
			{
				return this.SecurityRoleHistoryId == default(Nullable<Int64>);
			}
			set
			{
				if(value)
					this.SecurityRoleHistoryId =  default(Nullable<Int64>);
			}
		}
		
		/* PRIMARY_KEY */
		public Nullable<Int64> @SecurityRoleHistoryId
		{
			get
			{
				return this.@securityRoleHistoryId;
			}
			set
			{
				this.@securityRoleHistoryId = value;
			}
		}
		
		public Nullable<DateTime> @SecurityRoleHistoryTs
		{
			get
			{
				return this.@securityRoleHistoryTs;
			}
			set
			{
				this.@securityRoleHistoryTs = value;
			}
		}
		
		public Nullable<Int32> @SecurityRoleId
		{
			get
			{
				return this.@securityRoleId;
			}
			set
			{
				this.@securityRoleId = value;
			}
		}
		
		public String @SecurityRoleName
		{
			get
			{
				return this.@securityRoleName;
			}
			set
			{
				this.@securityRoleName = value;
			}
		}
		
		public Nullable<Byte> @SortOrder
		{
			get
			{
				return this.@sortOrder;
			}
			set
			{
				this.@sortOrder = value;
			}
		}
		
		public Nullable<DateTime> @CreationTimestamp
		{
			get
			{
				return this.@creationTimestamp;
			}
			set
			{
				this.@creationTimestamp = value;
			}
		}
		
		public Nullable<DateTime> @ModificationTimestamp
		{
			get
			{
				return this.@modificationTimestamp;
			}
			set
			{
				this.@modificationTimestamp = value;
			}
		}
		
		public Nullable<Int32> @CreationUserId
		{
			get
			{
				return this.@creationUserId;
			}
			set
			{
				this.@creationUserId = value;
			}
		}
		
		public Nullable<Int32> @ModificationUserId
		{
			get
			{
				return this.@modificationUserId;
			}
			set
			{
				this.@modificationUserId = value;
			}
		}
		
		public Nullable<Boolean> @LogicalDelete
		{
			get
			{
				return this.@logicalDelete;
			}
			set
			{
				this.@logicalDelete = value;
			}
		}
		
		#endregion
	}
}
