//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by:
// TextMetal 5.0.6.35568;
// 		Copyright ©2002-2014 Daniel Bullington (dpbullington@gmail.com)
//		Distributed under the MIT license: http://www.opensource.org/licenses/mit-license.php
//		Project URL: https://github.com/dpbullington/textmetal
//
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//
// </auto-generated>
//------------------------------------------------------------------------------

/*
	Copyright ©2002-2014 Daniel Bullington (dpbullington@gmail.com)
	Distributed under the MIT license: http://www.opensource.org/licenses/mit-license.php
*/

using System;
using System.Xml;

using TextMetal.Common.Core;

namespace TextMetal.HostImpl.AspNetSample.DomainModel.Tables
{
	public partial class TabWithNoPrimaryKeyWithIdentity : Object
	{		
		#region Constructors/Destructors
		
		public TabWithNoPrimaryKeyWithIdentity()
		{
		}
		
		#endregion
		
		#region Fields/Constants

		private Nullable<Int32> @colIntId;
		private Nullable<Int64> @colBigint;
		private Byte[] @colBinary;
		private Nullable<Boolean> @colBit;
		private String @colChar;
		private Nullable<DateTime> @colDate;
		private Nullable<DateTime> @colDatetime;
		private Nullable<DateTime> @colDatetime2;
		private Nullable<DateTimeOffset> @colDatetimeoffset;
		private Nullable<Decimal> @colDecimal;
		private Nullable<Double> @colFloat;
		private Byte[] @colImage;
		private Nullable<Int32> @colInt;
		private Nullable<Decimal> @colMoney;
		private String @colNchar;
		private String @colNtext;
		private Nullable<Decimal> @colNumeric;
		private String @colNvarchar;
		private Nullable<Single> @colReal;
		private Byte[] @colRowversion;
		private Nullable<DateTime> @colSmalldatetime;
		private Nullable<Int16> @colSmallint;
		private Nullable<Decimal> @colSmallmoney;
		private Object @colSqlVariant;
		private String @colSysname;
		private String @colText;
		private Nullable<TimeSpan> @colTime;
		private Nullable<Byte> @colTinyint;
		private Nullable<Guid> @colUniqueidentifier;
		private Byte[] @colVarbinary;
		private String @colVarchar;
		private XmlDocument @colXml;

		#endregion

		#region Properties/Indexers/Events
		
		public virtual bool IsNew
		{
			get
			{
				return this.ColIntId == default(Nullable<Int32>);
			}
			set
			{
				if(value)
					this.ColIntId =  default(Nullable<Int32>);
			}
		}
		
		/* PRIMARY_KEY */
		public Nullable<Int32> @ColIntId
		{
			get
			{
				return this.@colIntId;
			}
			set
			{
				this.@colIntId = value;
			}
		}
		
		/* PRIMARY_KEY */
		public Nullable<Int64> @ColBigint
		{
			get
			{
				return this.@colBigint;
			}
			set
			{
				this.@colBigint = value;
			}
		}
		
		/* PRIMARY_KEY */
		public Byte[] @ColBinary
		{
			get
			{
				return this.@colBinary;
			}
			set
			{
				this.@colBinary = value;
			}
		}
		
		/* PRIMARY_KEY */
		public Nullable<Boolean> @ColBit
		{
			get
			{
				return this.@colBit;
			}
			set
			{
				this.@colBit = value;
			}
		}
		
		/* PRIMARY_KEY */
		public String @ColChar
		{
			get
			{
				return this.@colChar;
			}
			set
			{
				this.@colChar = value;
			}
		}
		
		/* PRIMARY_KEY */
		public Nullable<DateTime> @ColDate
		{
			get
			{
				return this.@colDate;
			}
			set
			{
				this.@colDate = value;
			}
		}
		
		/* PRIMARY_KEY */
		public Nullable<DateTime> @ColDatetime
		{
			get
			{
				return this.@colDatetime;
			}
			set
			{
				this.@colDatetime = value;
			}
		}
		
		/* PRIMARY_KEY */
		public Nullable<DateTime> @ColDatetime2
		{
			get
			{
				return this.@colDatetime2;
			}
			set
			{
				this.@colDatetime2 = value;
			}
		}
		
		/* PRIMARY_KEY */
		public Nullable<DateTimeOffset> @ColDatetimeoffset
		{
			get
			{
				return this.@colDatetimeoffset;
			}
			set
			{
				this.@colDatetimeoffset = value;
			}
		}
		
		/* PRIMARY_KEY */
		public Nullable<Decimal> @ColDecimal
		{
			get
			{
				return this.@colDecimal;
			}
			set
			{
				this.@colDecimal = value;
			}
		}
		
		/* PRIMARY_KEY */
		public Nullable<Double> @ColFloat
		{
			get
			{
				return this.@colFloat;
			}
			set
			{
				this.@colFloat = value;
			}
		}
		
		/* PRIMARY_KEY */
		public Byte[] @ColImage
		{
			get
			{
				return this.@colImage;
			}
			set
			{
				this.@colImage = value;
			}
		}
		
		/* PRIMARY_KEY */
		public Nullable<Int32> @ColInt
		{
			get
			{
				return this.@colInt;
			}
			set
			{
				this.@colInt = value;
			}
		}
		
		/* PRIMARY_KEY */
		public Nullable<Decimal> @ColMoney
		{
			get
			{
				return this.@colMoney;
			}
			set
			{
				this.@colMoney = value;
			}
		}
		
		/* PRIMARY_KEY */
		public String @ColNchar
		{
			get
			{
				return this.@colNchar;
			}
			set
			{
				this.@colNchar = value;
			}
		}
		
		/* PRIMARY_KEY */
		public String @ColNtext
		{
			get
			{
				return this.@colNtext;
			}
			set
			{
				this.@colNtext = value;
			}
		}
		
		/* PRIMARY_KEY */
		public Nullable<Decimal> @ColNumeric
		{
			get
			{
				return this.@colNumeric;
			}
			set
			{
				this.@colNumeric = value;
			}
		}
		
		/* PRIMARY_KEY */
		public String @ColNvarchar
		{
			get
			{
				return this.@colNvarchar;
			}
			set
			{
				this.@colNvarchar = value;
			}
		}
		
		/* PRIMARY_KEY */
		public Nullable<Single> @ColReal
		{
			get
			{
				return this.@colReal;
			}
			set
			{
				this.@colReal = value;
			}
		}
		
		/* PRIMARY_KEY */
		public Byte[] @ColRowversion
		{
			get
			{
				return this.@colRowversion;
			}
			set
			{
				this.@colRowversion = value;
			}
		}
		
		/* PRIMARY_KEY */
		public Nullable<DateTime> @ColSmalldatetime
		{
			get
			{
				return this.@colSmalldatetime;
			}
			set
			{
				this.@colSmalldatetime = value;
			}
		}
		
		/* PRIMARY_KEY */
		public Nullable<Int16> @ColSmallint
		{
			get
			{
				return this.@colSmallint;
			}
			set
			{
				this.@colSmallint = value;
			}
		}
		
		/* PRIMARY_KEY */
		public Nullable<Decimal> @ColSmallmoney
		{
			get
			{
				return this.@colSmallmoney;
			}
			set
			{
				this.@colSmallmoney = value;
			}
		}
		
		/* PRIMARY_KEY */
		public Object @ColSqlVariant
		{
			get
			{
				return this.@colSqlVariant;
			}
			set
			{
				this.@colSqlVariant = value;
			}
		}
		
		/* PRIMARY_KEY */
		public String @ColSysname
		{
			get
			{
				return this.@colSysname;
			}
			set
			{
				this.@colSysname = value;
			}
		}
		
		/* PRIMARY_KEY */
		public String @ColText
		{
			get
			{
				return this.@colText;
			}
			set
			{
				this.@colText = value;
			}
		}
		
		/* PRIMARY_KEY */
		public Nullable<TimeSpan> @ColTime
		{
			get
			{
				return this.@colTime;
			}
			set
			{
				this.@colTime = value;
			}
		}
		
		/* PRIMARY_KEY */
		public Nullable<Byte> @ColTinyint
		{
			get
			{
				return this.@colTinyint;
			}
			set
			{
				this.@colTinyint = value;
			}
		}
		
		/* PRIMARY_KEY */
		public Nullable<Guid> @ColUniqueidentifier
		{
			get
			{
				return this.@colUniqueidentifier;
			}
			set
			{
				this.@colUniqueidentifier = value;
			}
		}
		
		/* PRIMARY_KEY */
		public Byte[] @ColVarbinary
		{
			get
			{
				return this.@colVarbinary;
			}
			set
			{
				this.@colVarbinary = value;
			}
		}
		
		/* PRIMARY_KEY */
		public String @ColVarchar
		{
			get
			{
				return this.@colVarchar;
			}
			set
			{
				this.@colVarchar = value;
			}
		}
		
		/* PRIMARY_KEY */
		public XmlDocument @ColXml
		{
			get
			{
				return this.@colXml;
			}
			set
			{
				this.@colXml = value;
			}
		}
		
		#endregion
	}
}
