//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by:
// TextMetal 5.0.3.597;
// 		Copyright ©2002-2013 Daniel Bullington (dpbullington@gmail.com)
//		Distributed under the MIT license: http://www.opensource.org/licenses/mit-license.php
//		Project URL: https://github.com/dpbullington/textmetal
//
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//
// </auto-generated>
//------------------------------------------------------------------------------

/*
	Copyright ©2002-2013 Daniel Bullington (dpbullington@gmail.com)
	Distributed under the MIT license: http://www.opensource.org/licenses/mit-license.php
*/

using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Linq;
using System.Linq;
using System.Xml;

using TextMetal.Common.Core;
using TextMetal.Common.Data;
using TextMetal.Common.Data.LinqToSql;

using TextMetal.HostImpl.AspNetSample.Objects.Model.Tables;
using TextMetal.HostImpl.AspNetSample.Objects.Model.Views;

namespace TextMetal.HostImpl.AspNetSample.Objects.Model
{
	public partial interface IRepository
	{		
		#region Methods/Operators
		
		User LoadUser(Int32 @userId);

		User LoadUser(IUnitOfWork unitOfWork, Int32 @userId);
						
		IEnumerable<User> FindUsers(Func<IQueryable<TextMetal.HostImpl.AspNetSample.Objects.Model.L2S.User>, IQueryable<TextMetal.HostImpl.AspNetSample.Objects.Model.L2S.User>> callback);
		
		IEnumerable<User> FindUsers(IUnitOfWork unitOfWork, Func<IQueryable<TextMetal.HostImpl.AspNetSample.Objects.Model.L2S.User>, IQueryable<TextMetal.HostImpl.AspNetSample.Objects.Model.L2S.User>> callback);
		
		bool SaveUser(User @user);
		
		bool SaveUser(IUnitOfWork unitOfWork, User @user);
		
		bool DiscardUser(User @user);
		
		bool DiscardUser(IUnitOfWork unitOfWork, User @user);

		EventLog LoadEventLog(Int32 @eventLogId);

		EventLog LoadEventLog(IUnitOfWork unitOfWork, Int32 @eventLogId);
						
		IEnumerable<EventLog> FindEventLogs(Func<IQueryable<TextMetal.HostImpl.AspNetSample.Objects.Model.L2S.EventLog>, IQueryable<TextMetal.HostImpl.AspNetSample.Objects.Model.L2S.EventLog>> callback);
		
		IEnumerable<EventLog> FindEventLogs(IUnitOfWork unitOfWork, Func<IQueryable<TextMetal.HostImpl.AspNetSample.Objects.Model.L2S.EventLog>, IQueryable<TextMetal.HostImpl.AspNetSample.Objects.Model.L2S.EventLog>> callback);
		
		bool SaveEventLog(EventLog @eventLog);
		
		bool SaveEventLog(IUnitOfWork unitOfWork, EventLog @eventLog);
		
		bool DiscardEventLog(EventLog @eventLog);
		
		bool DiscardEventLog(IUnitOfWork unitOfWork, EventLog @eventLog);

		EmailMessage LoadEmailMessage(Int32 @emailMessageId);

		EmailMessage LoadEmailMessage(IUnitOfWork unitOfWork, Int32 @emailMessageId);
						
		IEnumerable<EmailMessage> FindEmailMessages(Func<IQueryable<TextMetal.HostImpl.AspNetSample.Objects.Model.L2S.EmailMessage>, IQueryable<TextMetal.HostImpl.AspNetSample.Objects.Model.L2S.EmailMessage>> callback);
		
		IEnumerable<EmailMessage> FindEmailMessages(IUnitOfWork unitOfWork, Func<IQueryable<TextMetal.HostImpl.AspNetSample.Objects.Model.L2S.EmailMessage>, IQueryable<TextMetal.HostImpl.AspNetSample.Objects.Model.L2S.EmailMessage>> callback);
		
		bool SaveEmailMessage(EmailMessage @emailMessage);
		
		bool SaveEmailMessage(IUnitOfWork unitOfWork, EmailMessage @emailMessage);
		
		bool DiscardEmailMessage(EmailMessage @emailMessage);
		
		bool DiscardEmailMessage(IUnitOfWork unitOfWork, EmailMessage @emailMessage);

		EmailAttachment LoadEmailAttachment(Int32 @emailMessageId);

		EmailAttachment LoadEmailAttachment(IUnitOfWork unitOfWork, Int32 @emailMessageId);
						
		IEnumerable<EmailAttachment> FindEmailAttachments(Func<IQueryable<TextMetal.HostImpl.AspNetSample.Objects.Model.L2S.EmailAttachment>, IQueryable<TextMetal.HostImpl.AspNetSample.Objects.Model.L2S.EmailAttachment>> callback);
		
		IEnumerable<EmailAttachment> FindEmailAttachments(IUnitOfWork unitOfWork, Func<IQueryable<TextMetal.HostImpl.AspNetSample.Objects.Model.L2S.EmailAttachment>, IQueryable<TextMetal.HostImpl.AspNetSample.Objects.Model.L2S.EmailAttachment>> callback);
		
		bool SaveEmailAttachment(EmailAttachment @emailAttachment);
		
		bool SaveEmailAttachment(IUnitOfWork unitOfWork, EmailAttachment @emailAttachment);
		
		bool DiscardEmailAttachment(EmailAttachment @emailAttachment);
		
		bool DiscardEmailAttachment(IUnitOfWork unitOfWork, EmailAttachment @emailAttachment);

		TableWithPrimaryKeyAsIdentity LoadTableWithPrimaryKeyAsIdentity(Int32 @pkId);

		TableWithPrimaryKeyAsIdentity LoadTableWithPrimaryKeyAsIdentity(IUnitOfWork unitOfWork, Int32 @pkId);
						
		IEnumerable<TableWithPrimaryKeyAsIdentity> FindTableWithPrimaryKeyAsIdentities(Func<IQueryable<TextMetal.HostImpl.AspNetSample.Objects.Model.L2S.TableWithPrimaryKeyAsIdentity>, IQueryable<TextMetal.HostImpl.AspNetSample.Objects.Model.L2S.TableWithPrimaryKeyAsIdentity>> callback);
		
		IEnumerable<TableWithPrimaryKeyAsIdentity> FindTableWithPrimaryKeyAsIdentities(IUnitOfWork unitOfWork, Func<IQueryable<TextMetal.HostImpl.AspNetSample.Objects.Model.L2S.TableWithPrimaryKeyAsIdentity>, IQueryable<TextMetal.HostImpl.AspNetSample.Objects.Model.L2S.TableWithPrimaryKeyAsIdentity>> callback);
		
		bool SaveTableWithPrimaryKeyAsIdentity(TableWithPrimaryKeyAsIdentity @tableWithPrimaryKeyAsIdentity);
		
		bool SaveTableWithPrimaryKeyAsIdentity(IUnitOfWork unitOfWork, TableWithPrimaryKeyAsIdentity @tableWithPrimaryKeyAsIdentity);
		
		bool DiscardTableWithPrimaryKeyAsIdentity(TableWithPrimaryKeyAsIdentity @tableWithPrimaryKeyAsIdentity);
		
		bool DiscardTableWithPrimaryKeyAsIdentity(IUnitOfWork unitOfWork, TableWithPrimaryKeyAsIdentity @tableWithPrimaryKeyAsIdentity);

		TableWithPrimaryKeyAsDefault LoadTableWithPrimaryKeyAsDefault(Guid @pkDf);

		TableWithPrimaryKeyAsDefault LoadTableWithPrimaryKeyAsDefault(IUnitOfWork unitOfWork, Guid @pkDf);
						
		IEnumerable<TableWithPrimaryKeyAsDefault> FindTableWithPrimaryKeyAsDefaults(Func<IQueryable<TextMetal.HostImpl.AspNetSample.Objects.Model.L2S.TableWithPrimaryKeyAsDefault>, IQueryable<TextMetal.HostImpl.AspNetSample.Objects.Model.L2S.TableWithPrimaryKeyAsDefault>> callback);
		
		IEnumerable<TableWithPrimaryKeyAsDefault> FindTableWithPrimaryKeyAsDefaults(IUnitOfWork unitOfWork, Func<IQueryable<TextMetal.HostImpl.AspNetSample.Objects.Model.L2S.TableWithPrimaryKeyAsDefault>, IQueryable<TextMetal.HostImpl.AspNetSample.Objects.Model.L2S.TableWithPrimaryKeyAsDefault>> callback);
		
		bool SaveTableWithPrimaryKeyAsDefault(TableWithPrimaryKeyAsDefault @tableWithPrimaryKeyAsDefault);
		
		bool SaveTableWithPrimaryKeyAsDefault(IUnitOfWork unitOfWork, TableWithPrimaryKeyAsDefault @tableWithPrimaryKeyAsDefault);
		
		bool DiscardTableWithPrimaryKeyAsDefault(TableWithPrimaryKeyAsDefault @tableWithPrimaryKeyAsDefault);
		
		bool DiscardTableWithPrimaryKeyAsDefault(IUnitOfWork unitOfWork, TableWithPrimaryKeyAsDefault @tableWithPrimaryKeyAsDefault);

		TableWithPrimaryKeyWithDiffIdentity LoadTableWithPrimaryKeyWithDiffIdentity(Int32 @pk);

		TableWithPrimaryKeyWithDiffIdentity LoadTableWithPrimaryKeyWithDiffIdentity(IUnitOfWork unitOfWork, Int32 @pk);
						
		IEnumerable<TableWithPrimaryKeyWithDiffIdentity> FindTableWithPrimaryKeyWithDiffIdentities(Func<IQueryable<TextMetal.HostImpl.AspNetSample.Objects.Model.L2S.TableWithPrimaryKeyWithDiffIdentity>, IQueryable<TextMetal.HostImpl.AspNetSample.Objects.Model.L2S.TableWithPrimaryKeyWithDiffIdentity>> callback);
		
		IEnumerable<TableWithPrimaryKeyWithDiffIdentity> FindTableWithPrimaryKeyWithDiffIdentities(IUnitOfWork unitOfWork, Func<IQueryable<TextMetal.HostImpl.AspNetSample.Objects.Model.L2S.TableWithPrimaryKeyWithDiffIdentity>, IQueryable<TextMetal.HostImpl.AspNetSample.Objects.Model.L2S.TableWithPrimaryKeyWithDiffIdentity>> callback);
		
		bool SaveTableWithPrimaryKeyWithDiffIdentity(TableWithPrimaryKeyWithDiffIdentity @tableWithPrimaryKeyWithDiffIdentity);
		
		bool SaveTableWithPrimaryKeyWithDiffIdentity(IUnitOfWork unitOfWork, TableWithPrimaryKeyWithDiffIdentity @tableWithPrimaryKeyWithDiffIdentity);
		
		bool DiscardTableWithPrimaryKeyWithDiffIdentity(TableWithPrimaryKeyWithDiffIdentity @tableWithPrimaryKeyWithDiffIdentity);
		
		bool DiscardTableWithPrimaryKeyWithDiffIdentity(IUnitOfWork unitOfWork, TableWithPrimaryKeyWithDiffIdentity @tableWithPrimaryKeyWithDiffIdentity);

		TableNoPrimaryKeyWithIdentity LoadTableNoPrimaryKeyWithIdentity(Int32 @id, Boolean @data01, DateTime @data02, Int32 @data03, String @data04);

		TableNoPrimaryKeyWithIdentity LoadTableNoPrimaryKeyWithIdentity(IUnitOfWork unitOfWork, Int32 @id, Boolean @data01, DateTime @data02, Int32 @data03, String @data04);
						
		IEnumerable<TableNoPrimaryKeyWithIdentity> FindTableNoPrimaryKeyWithIdentities(Func<IQueryable<TextMetal.HostImpl.AspNetSample.Objects.Model.L2S.TableNoPrimaryKeyWithIdentity>, IQueryable<TextMetal.HostImpl.AspNetSample.Objects.Model.L2S.TableNoPrimaryKeyWithIdentity>> callback);
		
		IEnumerable<TableNoPrimaryKeyWithIdentity> FindTableNoPrimaryKeyWithIdentities(IUnitOfWork unitOfWork, Func<IQueryable<TextMetal.HostImpl.AspNetSample.Objects.Model.L2S.TableNoPrimaryKeyWithIdentity>, IQueryable<TextMetal.HostImpl.AspNetSample.Objects.Model.L2S.TableNoPrimaryKeyWithIdentity>> callback);
		
		bool SaveTableNoPrimaryKeyWithIdentity(TableNoPrimaryKeyWithIdentity @tableNoPrimaryKeyWithIdentity);
		
		bool SaveTableNoPrimaryKeyWithIdentity(IUnitOfWork unitOfWork, TableNoPrimaryKeyWithIdentity @tableNoPrimaryKeyWithIdentity);
		
		bool DiscardTableNoPrimaryKeyWithIdentity(TableNoPrimaryKeyWithIdentity @tableNoPrimaryKeyWithIdentity);
		
		bool DiscardTableNoPrimaryKeyWithIdentity(IUnitOfWork unitOfWork, TableNoPrimaryKeyWithIdentity @tableNoPrimaryKeyWithIdentity);

		TableWithPrimaryKeyNoIdentity LoadTableWithPrimaryKeyNoIdentity(Int32 @pk);

		TableWithPrimaryKeyNoIdentity LoadTableWithPrimaryKeyNoIdentity(IUnitOfWork unitOfWork, Int32 @pk);
						
		IEnumerable<TableWithPrimaryKeyNoIdentity> FindTableWithPrimaryKeyNoIdentities(Func<IQueryable<TextMetal.HostImpl.AspNetSample.Objects.Model.L2S.TableWithPrimaryKeyNoIdentity>, IQueryable<TextMetal.HostImpl.AspNetSample.Objects.Model.L2S.TableWithPrimaryKeyNoIdentity>> callback);
		
		IEnumerable<TableWithPrimaryKeyNoIdentity> FindTableWithPrimaryKeyNoIdentities(IUnitOfWork unitOfWork, Func<IQueryable<TextMetal.HostImpl.AspNetSample.Objects.Model.L2S.TableWithPrimaryKeyNoIdentity>, IQueryable<TextMetal.HostImpl.AspNetSample.Objects.Model.L2S.TableWithPrimaryKeyNoIdentity>> callback);
		
		bool SaveTableWithPrimaryKeyNoIdentity(TableWithPrimaryKeyNoIdentity @tableWithPrimaryKeyNoIdentity);
		
		bool SaveTableWithPrimaryKeyNoIdentity(IUnitOfWork unitOfWork, TableWithPrimaryKeyNoIdentity @tableWithPrimaryKeyNoIdentity);
		
		bool DiscardTableWithPrimaryKeyNoIdentity(TableWithPrimaryKeyNoIdentity @tableWithPrimaryKeyNoIdentity);
		
		bool DiscardTableWithPrimaryKeyNoIdentity(IUnitOfWork unitOfWork, TableWithPrimaryKeyNoIdentity @tableWithPrimaryKeyNoIdentity);

		TableWithCompositePrimaryKeyNoIdentity LoadTableWithCompositePrimaryKeyNoIdentity(Int32 @pk0, Int32 @pk1, Int32 @pk2, Int32 @pk3);

		TableWithCompositePrimaryKeyNoIdentity LoadTableWithCompositePrimaryKeyNoIdentity(IUnitOfWork unitOfWork, Int32 @pk0, Int32 @pk1, Int32 @pk2, Int32 @pk3);
						
		IEnumerable<TableWithCompositePrimaryKeyNoIdentity> FindTableWithCompositePrimaryKeyNoIdentities(Func<IQueryable<TextMetal.HostImpl.AspNetSample.Objects.Model.L2S.TableWithCompositePrimaryKeyNoIdentity>, IQueryable<TextMetal.HostImpl.AspNetSample.Objects.Model.L2S.TableWithCompositePrimaryKeyNoIdentity>> callback);
		
		IEnumerable<TableWithCompositePrimaryKeyNoIdentity> FindTableWithCompositePrimaryKeyNoIdentities(IUnitOfWork unitOfWork, Func<IQueryable<TextMetal.HostImpl.AspNetSample.Objects.Model.L2S.TableWithCompositePrimaryKeyNoIdentity>, IQueryable<TextMetal.HostImpl.AspNetSample.Objects.Model.L2S.TableWithCompositePrimaryKeyNoIdentity>> callback);
		
		bool SaveTableWithCompositePrimaryKeyNoIdentity(TableWithCompositePrimaryKeyNoIdentity @tableWithCompositePrimaryKeyNoIdentity);
		
		bool SaveTableWithCompositePrimaryKeyNoIdentity(IUnitOfWork unitOfWork, TableWithCompositePrimaryKeyNoIdentity @tableWithCompositePrimaryKeyNoIdentity);
		
		bool DiscardTableWithCompositePrimaryKeyNoIdentity(TableWithCompositePrimaryKeyNoIdentity @tableWithCompositePrimaryKeyNoIdentity);
		
		bool DiscardTableWithCompositePrimaryKeyNoIdentity(IUnitOfWork unitOfWork, TableWithCompositePrimaryKeyNoIdentity @tableWithCompositePrimaryKeyNoIdentity);

		TableNoPrimaryKeyNoIdentity LoadTableNoPrimaryKeyNoIdentity(Int32 @value, Boolean @data01, DateTime @data02, Int32 @data03, String @data04);

		TableNoPrimaryKeyNoIdentity LoadTableNoPrimaryKeyNoIdentity(IUnitOfWork unitOfWork, Int32 @value, Boolean @data01, DateTime @data02, Int32 @data03, String @data04);
						
		IEnumerable<TableNoPrimaryKeyNoIdentity> FindTableNoPrimaryKeyNoIdentities(Func<IQueryable<TextMetal.HostImpl.AspNetSample.Objects.Model.L2S.TableNoPrimaryKeyNoIdentity>, IQueryable<TextMetal.HostImpl.AspNetSample.Objects.Model.L2S.TableNoPrimaryKeyNoIdentity>> callback);
		
		IEnumerable<TableNoPrimaryKeyNoIdentity> FindTableNoPrimaryKeyNoIdentities(IUnitOfWork unitOfWork, Func<IQueryable<TextMetal.HostImpl.AspNetSample.Objects.Model.L2S.TableNoPrimaryKeyNoIdentity>, IQueryable<TextMetal.HostImpl.AspNetSample.Objects.Model.L2S.TableNoPrimaryKeyNoIdentity>> callback);
		
		bool SaveTableNoPrimaryKeyNoIdentity(TableNoPrimaryKeyNoIdentity @tableNoPrimaryKeyNoIdentity);
		
		bool SaveTableNoPrimaryKeyNoIdentity(IUnitOfWork unitOfWork, TableNoPrimaryKeyNoIdentity @tableNoPrimaryKeyNoIdentity);
		
		bool DiscardTableNoPrimaryKeyNoIdentity(TableNoPrimaryKeyNoIdentity @tableNoPrimaryKeyNoIdentity);
		
		bool DiscardTableNoPrimaryKeyNoIdentity(IUnitOfWork unitOfWork, TableNoPrimaryKeyNoIdentity @tableNoPrimaryKeyNoIdentity);

		TableTypeTest LoadTableTypeTest(Int32 @pkId);

		TableTypeTest LoadTableTypeTest(IUnitOfWork unitOfWork, Int32 @pkId);
						
		IEnumerable<TableTypeTest> FindTableTypeTests(Func<IQueryable<TextMetal.HostImpl.AspNetSample.Objects.Model.L2S.TableTypeTest>, IQueryable<TextMetal.HostImpl.AspNetSample.Objects.Model.L2S.TableTypeTest>> callback);
		
		IEnumerable<TableTypeTest> FindTableTypeTests(IUnitOfWork unitOfWork, Func<IQueryable<TextMetal.HostImpl.AspNetSample.Objects.Model.L2S.TableTypeTest>, IQueryable<TextMetal.HostImpl.AspNetSample.Objects.Model.L2S.TableTypeTest>> callback);
		
		bool SaveTableTypeTest(TableTypeTest @tableTypeTest);
		
		bool SaveTableTypeTest(IUnitOfWork unitOfWork, TableTypeTest @tableTypeTest);
		
		bool DiscardTableTypeTest(TableTypeTest @tableTypeTest);
		
		bool DiscardTableTypeTest(IUnitOfWork unitOfWork, TableTypeTest @tableTypeTest);

		EventLogAggregation LoadEventLogAggregation(DateTime @minCreationTimestamp, DateTime @maxModificationTimestamp);

		EventLogAggregation LoadEventLogAggregation(IUnitOfWork unitOfWork, DateTime @minCreationTimestamp, DateTime @maxModificationTimestamp);
						
		IEnumerable<EventLogAggregation> FindEventLogAggregations(Func<IQueryable<TextMetal.HostImpl.AspNetSample.Objects.Model.L2S.EventLogAggregation>, IQueryable<TextMetal.HostImpl.AspNetSample.Objects.Model.L2S.EventLogAggregation>> callback);
		
		IEnumerable<EventLogAggregation> FindEventLogAggregations(IUnitOfWork unitOfWork, Func<IQueryable<TextMetal.HostImpl.AspNetSample.Objects.Model.L2S.EventLogAggregation>, IQueryable<TextMetal.HostImpl.AspNetSample.Objects.Model.L2S.EventLogAggregation>> callback);
		
		bool SaveEventLogAggregation(EventLogAggregation @eventLogAggregation);
		
		bool SaveEventLogAggregation(IUnitOfWork unitOfWork, EventLogAggregation @eventLogAggregation);
		
		bool DiscardEventLogAggregation(EventLogAggregation @eventLogAggregation);
		
		bool DiscardEventLogAggregation(IUnitOfWork unitOfWork, EventLogAggregation @eventLogAggregation);
		UserHistory LoadUserHistory(Int64 @timestampId, Int32 @userId);

		UserHistory LoadUserHistory(IUnitOfWork unitOfWork, Int64 @timestampId, Int32 @userId);
						
		IEnumerable<UserHistory> FindUserHistories(Func<IQueryable<TextMetal.HostImpl.AspNetSample.Objects.Model.L2S.UserHistory>, IQueryable<TextMetal.HostImpl.AspNetSample.Objects.Model.L2S.UserHistory>> callback);
		
		IEnumerable<UserHistory> FindUserHistories(IUnitOfWork unitOfWork, Func<IQueryable<TextMetal.HostImpl.AspNetSample.Objects.Model.L2S.UserHistory>, IQueryable<TextMetal.HostImpl.AspNetSample.Objects.Model.L2S.UserHistory>> callback);
		
		bool SaveUserHistory(UserHistory @userHistory);
		
		bool SaveUserHistory(IUnitOfWork unitOfWork, UserHistory @userHistory);
		
		bool DiscardUserHistory(UserHistory @userHistory);
		
		bool DiscardUserHistory(IUnitOfWork unitOfWork, UserHistory @userHistory);

		EventLogHistory LoadEventLogHistory(Int64 @timestampId, Int32 @eventLogId);

		EventLogHistory LoadEventLogHistory(IUnitOfWork unitOfWork, Int64 @timestampId, Int32 @eventLogId);
						
		IEnumerable<EventLogHistory> FindEventLogHistories(Func<IQueryable<TextMetal.HostImpl.AspNetSample.Objects.Model.L2S.EventLogHistory>, IQueryable<TextMetal.HostImpl.AspNetSample.Objects.Model.L2S.EventLogHistory>> callback);
		
		IEnumerable<EventLogHistory> FindEventLogHistories(IUnitOfWork unitOfWork, Func<IQueryable<TextMetal.HostImpl.AspNetSample.Objects.Model.L2S.EventLogHistory>, IQueryable<TextMetal.HostImpl.AspNetSample.Objects.Model.L2S.EventLogHistory>> callback);
		
		bool SaveEventLogHistory(EventLogHistory @eventLogHistory);
		
		bool SaveEventLogHistory(IUnitOfWork unitOfWork, EventLogHistory @eventLogHistory);
		
		bool DiscardEventLogHistory(EventLogHistory @eventLogHistory);
		
		bool DiscardEventLogHistory(IUnitOfWork unitOfWork, EventLogHistory @eventLogHistory);

		EmailMessageHistory LoadEmailMessageHistory(Int64 @timestampId, Int32 @emailMessageId);

		EmailMessageHistory LoadEmailMessageHistory(IUnitOfWork unitOfWork, Int64 @timestampId, Int32 @emailMessageId);
						
		IEnumerable<EmailMessageHistory> FindEmailMessageHistories(Func<IQueryable<TextMetal.HostImpl.AspNetSample.Objects.Model.L2S.EmailMessageHistory>, IQueryable<TextMetal.HostImpl.AspNetSample.Objects.Model.L2S.EmailMessageHistory>> callback);
		
		IEnumerable<EmailMessageHistory> FindEmailMessageHistories(IUnitOfWork unitOfWork, Func<IQueryable<TextMetal.HostImpl.AspNetSample.Objects.Model.L2S.EmailMessageHistory>, IQueryable<TextMetal.HostImpl.AspNetSample.Objects.Model.L2S.EmailMessageHistory>> callback);
		
		bool SaveEmailMessageHistory(EmailMessageHistory @emailMessageHistory);
		
		bool SaveEmailMessageHistory(IUnitOfWork unitOfWork, EmailMessageHistory @emailMessageHistory);
		
		bool DiscardEmailMessageHistory(EmailMessageHistory @emailMessageHistory);
		
		bool DiscardEmailMessageHistory(IUnitOfWork unitOfWork, EmailMessageHistory @emailMessageHistory);

		EmailAttachmentHistory LoadEmailAttachmentHistory(Int64 @timestampId, Int32 @emailMessageId);

		EmailAttachmentHistory LoadEmailAttachmentHistory(IUnitOfWork unitOfWork, Int64 @timestampId, Int32 @emailMessageId);
						
		IEnumerable<EmailAttachmentHistory> FindEmailAttachmentHistories(Func<IQueryable<TextMetal.HostImpl.AspNetSample.Objects.Model.L2S.EmailAttachmentHistory>, IQueryable<TextMetal.HostImpl.AspNetSample.Objects.Model.L2S.EmailAttachmentHistory>> callback);
		
		IEnumerable<EmailAttachmentHistory> FindEmailAttachmentHistories(IUnitOfWork unitOfWork, Func<IQueryable<TextMetal.HostImpl.AspNetSample.Objects.Model.L2S.EmailAttachmentHistory>, IQueryable<TextMetal.HostImpl.AspNetSample.Objects.Model.L2S.EmailAttachmentHistory>> callback);
		
		bool SaveEmailAttachmentHistory(EmailAttachmentHistory @emailAttachmentHistory);
		
		bool SaveEmailAttachmentHistory(IUnitOfWork unitOfWork, EmailAttachmentHistory @emailAttachmentHistory);
		
		bool DiscardEmailAttachmentHistory(EmailAttachmentHistory @emailAttachmentHistory);
		
		bool DiscardEmailAttachmentHistory(IUnitOfWork unitOfWork, EmailAttachmentHistory @emailAttachmentHistory);

		TableWithPrimaryKeyAsIdentityHistory LoadTableWithPrimaryKeyAsIdentityHistory(Int64 @timestampId, Int32 @pkId);

		TableWithPrimaryKeyAsIdentityHistory LoadTableWithPrimaryKeyAsIdentityHistory(IUnitOfWork unitOfWork, Int64 @timestampId, Int32 @pkId);
						
		IEnumerable<TableWithPrimaryKeyAsIdentityHistory> FindTableWithPrimaryKeyAsIdentityHistories(Func<IQueryable<TextMetal.HostImpl.AspNetSample.Objects.Model.L2S.TableWithPrimaryKeyAsIdentityHistory>, IQueryable<TextMetal.HostImpl.AspNetSample.Objects.Model.L2S.TableWithPrimaryKeyAsIdentityHistory>> callback);
		
		IEnumerable<TableWithPrimaryKeyAsIdentityHistory> FindTableWithPrimaryKeyAsIdentityHistories(IUnitOfWork unitOfWork, Func<IQueryable<TextMetal.HostImpl.AspNetSample.Objects.Model.L2S.TableWithPrimaryKeyAsIdentityHistory>, IQueryable<TextMetal.HostImpl.AspNetSample.Objects.Model.L2S.TableWithPrimaryKeyAsIdentityHistory>> callback);
		
		bool SaveTableWithPrimaryKeyAsIdentityHistory(TableWithPrimaryKeyAsIdentityHistory @tableWithPrimaryKeyAsIdentityHistory);
		
		bool SaveTableWithPrimaryKeyAsIdentityHistory(IUnitOfWork unitOfWork, TableWithPrimaryKeyAsIdentityHistory @tableWithPrimaryKeyAsIdentityHistory);
		
		bool DiscardTableWithPrimaryKeyAsIdentityHistory(TableWithPrimaryKeyAsIdentityHistory @tableWithPrimaryKeyAsIdentityHistory);
		
		bool DiscardTableWithPrimaryKeyAsIdentityHistory(IUnitOfWork unitOfWork, TableWithPrimaryKeyAsIdentityHistory @tableWithPrimaryKeyAsIdentityHistory);

		TableWithPrimaryKeyAsDefaultHistory LoadTableWithPrimaryKeyAsDefaultHistory(Int64 @timestampId, Guid @pkDf);

		TableWithPrimaryKeyAsDefaultHistory LoadTableWithPrimaryKeyAsDefaultHistory(IUnitOfWork unitOfWork, Int64 @timestampId, Guid @pkDf);
						
		IEnumerable<TableWithPrimaryKeyAsDefaultHistory> FindTableWithPrimaryKeyAsDefaultHistories(Func<IQueryable<TextMetal.HostImpl.AspNetSample.Objects.Model.L2S.TableWithPrimaryKeyAsDefaultHistory>, IQueryable<TextMetal.HostImpl.AspNetSample.Objects.Model.L2S.TableWithPrimaryKeyAsDefaultHistory>> callback);
		
		IEnumerable<TableWithPrimaryKeyAsDefaultHistory> FindTableWithPrimaryKeyAsDefaultHistories(IUnitOfWork unitOfWork, Func<IQueryable<TextMetal.HostImpl.AspNetSample.Objects.Model.L2S.TableWithPrimaryKeyAsDefaultHistory>, IQueryable<TextMetal.HostImpl.AspNetSample.Objects.Model.L2S.TableWithPrimaryKeyAsDefaultHistory>> callback);
		
		bool SaveTableWithPrimaryKeyAsDefaultHistory(TableWithPrimaryKeyAsDefaultHistory @tableWithPrimaryKeyAsDefaultHistory);
		
		bool SaveTableWithPrimaryKeyAsDefaultHistory(IUnitOfWork unitOfWork, TableWithPrimaryKeyAsDefaultHistory @tableWithPrimaryKeyAsDefaultHistory);
		
		bool DiscardTableWithPrimaryKeyAsDefaultHistory(TableWithPrimaryKeyAsDefaultHistory @tableWithPrimaryKeyAsDefaultHistory);
		
		bool DiscardTableWithPrimaryKeyAsDefaultHistory(IUnitOfWork unitOfWork, TableWithPrimaryKeyAsDefaultHistory @tableWithPrimaryKeyAsDefaultHistory);

		TableWithPrimaryKeyWithDiffIdentityHistory LoadTableWithPrimaryKeyWithDiffIdentityHistory(Int64 @timestampId, Int32 @pk);

		TableWithPrimaryKeyWithDiffIdentityHistory LoadTableWithPrimaryKeyWithDiffIdentityHistory(IUnitOfWork unitOfWork, Int64 @timestampId, Int32 @pk);
						
		IEnumerable<TableWithPrimaryKeyWithDiffIdentityHistory> FindTableWithPrimaryKeyWithDiffIdentityHistories(Func<IQueryable<TextMetal.HostImpl.AspNetSample.Objects.Model.L2S.TableWithPrimaryKeyWithDiffIdentityHistory>, IQueryable<TextMetal.HostImpl.AspNetSample.Objects.Model.L2S.TableWithPrimaryKeyWithDiffIdentityHistory>> callback);
		
		IEnumerable<TableWithPrimaryKeyWithDiffIdentityHistory> FindTableWithPrimaryKeyWithDiffIdentityHistories(IUnitOfWork unitOfWork, Func<IQueryable<TextMetal.HostImpl.AspNetSample.Objects.Model.L2S.TableWithPrimaryKeyWithDiffIdentityHistory>, IQueryable<TextMetal.HostImpl.AspNetSample.Objects.Model.L2S.TableWithPrimaryKeyWithDiffIdentityHistory>> callback);
		
		bool SaveTableWithPrimaryKeyWithDiffIdentityHistory(TableWithPrimaryKeyWithDiffIdentityHistory @tableWithPrimaryKeyWithDiffIdentityHistory);
		
		bool SaveTableWithPrimaryKeyWithDiffIdentityHistory(IUnitOfWork unitOfWork, TableWithPrimaryKeyWithDiffIdentityHistory @tableWithPrimaryKeyWithDiffIdentityHistory);
		
		bool DiscardTableWithPrimaryKeyWithDiffIdentityHistory(TableWithPrimaryKeyWithDiffIdentityHistory @tableWithPrimaryKeyWithDiffIdentityHistory);
		
		bool DiscardTableWithPrimaryKeyWithDiffIdentityHistory(IUnitOfWork unitOfWork, TableWithPrimaryKeyWithDiffIdentityHistory @tableWithPrimaryKeyWithDiffIdentityHistory);

		TableNoPrimaryKeyWithIdentityHistory LoadTableNoPrimaryKeyWithIdentityHistory(Int64 @timestampId, Int32 @id, Boolean @data01, DateTime @data02, Int32 @data03, String @data04);

		TableNoPrimaryKeyWithIdentityHistory LoadTableNoPrimaryKeyWithIdentityHistory(IUnitOfWork unitOfWork, Int64 @timestampId, Int32 @id, Boolean @data01, DateTime @data02, Int32 @data03, String @data04);
						
		IEnumerable<TableNoPrimaryKeyWithIdentityHistory> FindTableNoPrimaryKeyWithIdentityHistories(Func<IQueryable<TextMetal.HostImpl.AspNetSample.Objects.Model.L2S.TableNoPrimaryKeyWithIdentityHistory>, IQueryable<TextMetal.HostImpl.AspNetSample.Objects.Model.L2S.TableNoPrimaryKeyWithIdentityHistory>> callback);
		
		IEnumerable<TableNoPrimaryKeyWithIdentityHistory> FindTableNoPrimaryKeyWithIdentityHistories(IUnitOfWork unitOfWork, Func<IQueryable<TextMetal.HostImpl.AspNetSample.Objects.Model.L2S.TableNoPrimaryKeyWithIdentityHistory>, IQueryable<TextMetal.HostImpl.AspNetSample.Objects.Model.L2S.TableNoPrimaryKeyWithIdentityHistory>> callback);
		
		bool SaveTableNoPrimaryKeyWithIdentityHistory(TableNoPrimaryKeyWithIdentityHistory @tableNoPrimaryKeyWithIdentityHistory);
		
		bool SaveTableNoPrimaryKeyWithIdentityHistory(IUnitOfWork unitOfWork, TableNoPrimaryKeyWithIdentityHistory @tableNoPrimaryKeyWithIdentityHistory);
		
		bool DiscardTableNoPrimaryKeyWithIdentityHistory(TableNoPrimaryKeyWithIdentityHistory @tableNoPrimaryKeyWithIdentityHistory);
		
		bool DiscardTableNoPrimaryKeyWithIdentityHistory(IUnitOfWork unitOfWork, TableNoPrimaryKeyWithIdentityHistory @tableNoPrimaryKeyWithIdentityHistory);

		TableWithPrimaryKeyNoIdentityHistory LoadTableWithPrimaryKeyNoIdentityHistory(Int64 @timestampId, Int32 @pk);

		TableWithPrimaryKeyNoIdentityHistory LoadTableWithPrimaryKeyNoIdentityHistory(IUnitOfWork unitOfWork, Int64 @timestampId, Int32 @pk);
						
		IEnumerable<TableWithPrimaryKeyNoIdentityHistory> FindTableWithPrimaryKeyNoIdentityHistories(Func<IQueryable<TextMetal.HostImpl.AspNetSample.Objects.Model.L2S.TableWithPrimaryKeyNoIdentityHistory>, IQueryable<TextMetal.HostImpl.AspNetSample.Objects.Model.L2S.TableWithPrimaryKeyNoIdentityHistory>> callback);
		
		IEnumerable<TableWithPrimaryKeyNoIdentityHistory> FindTableWithPrimaryKeyNoIdentityHistories(IUnitOfWork unitOfWork, Func<IQueryable<TextMetal.HostImpl.AspNetSample.Objects.Model.L2S.TableWithPrimaryKeyNoIdentityHistory>, IQueryable<TextMetal.HostImpl.AspNetSample.Objects.Model.L2S.TableWithPrimaryKeyNoIdentityHistory>> callback);
		
		bool SaveTableWithPrimaryKeyNoIdentityHistory(TableWithPrimaryKeyNoIdentityHistory @tableWithPrimaryKeyNoIdentityHistory);
		
		bool SaveTableWithPrimaryKeyNoIdentityHistory(IUnitOfWork unitOfWork, TableWithPrimaryKeyNoIdentityHistory @tableWithPrimaryKeyNoIdentityHistory);
		
		bool DiscardTableWithPrimaryKeyNoIdentityHistory(TableWithPrimaryKeyNoIdentityHistory @tableWithPrimaryKeyNoIdentityHistory);
		
		bool DiscardTableWithPrimaryKeyNoIdentityHistory(IUnitOfWork unitOfWork, TableWithPrimaryKeyNoIdentityHistory @tableWithPrimaryKeyNoIdentityHistory);

		TableWithCompositePrimaryKeyNoIdentityHistory LoadTableWithCompositePrimaryKeyNoIdentityHistory(Int64 @timestampId, Int32 @pk0, Int32 @pk1, Int32 @pk2, Int32 @pk3);

		TableWithCompositePrimaryKeyNoIdentityHistory LoadTableWithCompositePrimaryKeyNoIdentityHistory(IUnitOfWork unitOfWork, Int64 @timestampId, Int32 @pk0, Int32 @pk1, Int32 @pk2, Int32 @pk3);
						
		IEnumerable<TableWithCompositePrimaryKeyNoIdentityHistory> FindTableWithCompositePrimaryKeyNoIdentityHistories(Func<IQueryable<TextMetal.HostImpl.AspNetSample.Objects.Model.L2S.TableWithCompositePrimaryKeyNoIdentityHistory>, IQueryable<TextMetal.HostImpl.AspNetSample.Objects.Model.L2S.TableWithCompositePrimaryKeyNoIdentityHistory>> callback);
		
		IEnumerable<TableWithCompositePrimaryKeyNoIdentityHistory> FindTableWithCompositePrimaryKeyNoIdentityHistories(IUnitOfWork unitOfWork, Func<IQueryable<TextMetal.HostImpl.AspNetSample.Objects.Model.L2S.TableWithCompositePrimaryKeyNoIdentityHistory>, IQueryable<TextMetal.HostImpl.AspNetSample.Objects.Model.L2S.TableWithCompositePrimaryKeyNoIdentityHistory>> callback);
		
		bool SaveTableWithCompositePrimaryKeyNoIdentityHistory(TableWithCompositePrimaryKeyNoIdentityHistory @tableWithCompositePrimaryKeyNoIdentityHistory);
		
		bool SaveTableWithCompositePrimaryKeyNoIdentityHistory(IUnitOfWork unitOfWork, TableWithCompositePrimaryKeyNoIdentityHistory @tableWithCompositePrimaryKeyNoIdentityHistory);
		
		bool DiscardTableWithCompositePrimaryKeyNoIdentityHistory(TableWithCompositePrimaryKeyNoIdentityHistory @tableWithCompositePrimaryKeyNoIdentityHistory);
		
		bool DiscardTableWithCompositePrimaryKeyNoIdentityHistory(IUnitOfWork unitOfWork, TableWithCompositePrimaryKeyNoIdentityHistory @tableWithCompositePrimaryKeyNoIdentityHistory);

		TableNoPrimaryKeyNoIdentityHistory LoadTableNoPrimaryKeyNoIdentityHistory(Int64 @timestampId, Int32 @value, Boolean @data01, DateTime @data02, Int32 @data03, String @data04);

		TableNoPrimaryKeyNoIdentityHistory LoadTableNoPrimaryKeyNoIdentityHistory(IUnitOfWork unitOfWork, Int64 @timestampId, Int32 @value, Boolean @data01, DateTime @data02, Int32 @data03, String @data04);
						
		IEnumerable<TableNoPrimaryKeyNoIdentityHistory> FindTableNoPrimaryKeyNoIdentityHistories(Func<IQueryable<TextMetal.HostImpl.AspNetSample.Objects.Model.L2S.TableNoPrimaryKeyNoIdentityHistory>, IQueryable<TextMetal.HostImpl.AspNetSample.Objects.Model.L2S.TableNoPrimaryKeyNoIdentityHistory>> callback);
		
		IEnumerable<TableNoPrimaryKeyNoIdentityHistory> FindTableNoPrimaryKeyNoIdentityHistories(IUnitOfWork unitOfWork, Func<IQueryable<TextMetal.HostImpl.AspNetSample.Objects.Model.L2S.TableNoPrimaryKeyNoIdentityHistory>, IQueryable<TextMetal.HostImpl.AspNetSample.Objects.Model.L2S.TableNoPrimaryKeyNoIdentityHistory>> callback);
		
		bool SaveTableNoPrimaryKeyNoIdentityHistory(TableNoPrimaryKeyNoIdentityHistory @tableNoPrimaryKeyNoIdentityHistory);
		
		bool SaveTableNoPrimaryKeyNoIdentityHistory(IUnitOfWork unitOfWork, TableNoPrimaryKeyNoIdentityHistory @tableNoPrimaryKeyNoIdentityHistory);
		
		bool DiscardTableNoPrimaryKeyNoIdentityHistory(TableNoPrimaryKeyNoIdentityHistory @tableNoPrimaryKeyNoIdentityHistory);
		
		bool DiscardTableNoPrimaryKeyNoIdentityHistory(IUnitOfWork unitOfWork, TableNoPrimaryKeyNoIdentityHistory @tableNoPrimaryKeyNoIdentityHistory);

		TableTypeTestHistory LoadTableTypeTestHistory(Int64 @timestampId, Int32 @pkId);

		TableTypeTestHistory LoadTableTypeTestHistory(IUnitOfWork unitOfWork, Int64 @timestampId, Int32 @pkId);
						
		IEnumerable<TableTypeTestHistory> FindTableTypeTestHistories(Func<IQueryable<TextMetal.HostImpl.AspNetSample.Objects.Model.L2S.TableTypeTestHistory>, IQueryable<TextMetal.HostImpl.AspNetSample.Objects.Model.L2S.TableTypeTestHistory>> callback);
		
		IEnumerable<TableTypeTestHistory> FindTableTypeTestHistories(IUnitOfWork unitOfWork, Func<IQueryable<TextMetal.HostImpl.AspNetSample.Objects.Model.L2S.TableTypeTestHistory>, IQueryable<TextMetal.HostImpl.AspNetSample.Objects.Model.L2S.TableTypeTestHistory>> callback);
		
		bool SaveTableTypeTestHistory(TableTypeTestHistory @tableTypeTestHistory);
		
		bool SaveTableTypeTestHistory(IUnitOfWork unitOfWork, TableTypeTestHistory @tableTypeTestHistory);
		
		bool DiscardTableTypeTestHistory(TableTypeTestHistory @tableTypeTestHistory);
		
		bool DiscardTableTypeTestHistory(IUnitOfWork unitOfWork, TableTypeTestHistory @tableTypeTestHistory);

		SexualChocolateHistory LoadSexualChocolateHistory(Int64 @timestampId, Int32 @sexualChocolateId);

		SexualChocolateHistory LoadSexualChocolateHistory(IUnitOfWork unitOfWork, Int64 @timestampId, Int32 @sexualChocolateId);
						
		IEnumerable<SexualChocolateHistory> FindSexualChocolateHistories(Func<IQueryable<TextMetal.HostImpl.AspNetSample.Objects.Model.L2S.SexualChocolateHistory>, IQueryable<TextMetal.HostImpl.AspNetSample.Objects.Model.L2S.SexualChocolateHistory>> callback);
		
		IEnumerable<SexualChocolateHistory> FindSexualChocolateHistories(IUnitOfWork unitOfWork, Func<IQueryable<TextMetal.HostImpl.AspNetSample.Objects.Model.L2S.SexualChocolateHistory>, IQueryable<TextMetal.HostImpl.AspNetSample.Objects.Model.L2S.SexualChocolateHistory>> callback);
		
		bool SaveSexualChocolateHistory(SexualChocolateHistory @sexualChocolateHistory);
		
		bool SaveSexualChocolateHistory(IUnitOfWork unitOfWork, SexualChocolateHistory @sexualChocolateHistory);
		
		bool DiscardSexualChocolateHistory(SexualChocolateHistory @sexualChocolateHistory);
		
		bool DiscardSexualChocolateHistory(IUnitOfWork unitOfWork, SexualChocolateHistory @sexualChocolateHistory);
		SexualChocolate LoadSexualChocolate(Int32 @sexualChocolateId);

		SexualChocolate LoadSexualChocolate(IUnitOfWork unitOfWork, Int32 @sexualChocolateId);
						
		IEnumerable<SexualChocolate> FindSexualChocolates(Func<IQueryable<TextMetal.HostImpl.AspNetSample.Objects.Model.L2S.SexualChocolate>, IQueryable<TextMetal.HostImpl.AspNetSample.Objects.Model.L2S.SexualChocolate>> callback);
		
		IEnumerable<SexualChocolate> FindSexualChocolates(IUnitOfWork unitOfWork, Func<IQueryable<TextMetal.HostImpl.AspNetSample.Objects.Model.L2S.SexualChocolate>, IQueryable<TextMetal.HostImpl.AspNetSample.Objects.Model.L2S.SexualChocolate>> callback);
		
		bool SaveSexualChocolate(SexualChocolate @sexualChocolate);
		
		bool SaveSexualChocolate(IUnitOfWork unitOfWork, SexualChocolate @sexualChocolate);
		
		bool DiscardSexualChocolate(SexualChocolate @sexualChocolate);
		
		bool DiscardSexualChocolate(IUnitOfWork unitOfWork, SexualChocolate @sexualChocolate);

		#endregion
	}
}
