//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by:
// TextMetal 5.0.3.40772;
// 		Copyright ©2002-2013 Daniel Bullington (dpbullington@gmail.com)
//		Distributed under the MIT license: http://www.opensource.org/licenses/mit-license.php
//		Project URL: https://github.com/dpbullington/textmetal
//
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//
// </auto-generated>
//------------------------------------------------------------------------------

/*
	Copyright ©2002-2013 Daniel Bullington (dpbullington@gmail.com)
	Distributed under the MIT license: http://www.opensource.org/licenses/mit-license.php
*/

using System;
using System.Xml;

using TextMetal.Common.Core;

namespace TextMetal.HostImpl.AspNetSample.Objects.Model.Views
{
	public partial class EventLogAggregation : Object
	{		
		#region Constructors/Destructors
		
		public EventLogAggregation()
		{
		}
		
		#endregion
		
		#region Fields/Constants

		private Nullable<DateTime> @minCreationTimestamp;
		private Nullable<DateTime> @maxModificationTimestamp;

		#endregion

		#region Properties/Indexers/Events
		
		public virtual bool IsNew
		{
			get
			{
				throw new InvalidOperationException("TODO (enhancement): add meaningful message");
			}
			set
			{
				throw new InvalidOperationException("TODO (enhancement): add meaningful message");
			}
		}
		
		/* PRIMARY_KEY */
		public Nullable<DateTime> @MinCreationTimestamp
		{
			get
			{
				return this.@minCreationTimestamp;
			}
			set
			{
				this.@minCreationTimestamp = value;
			}
		}
		
		/* PRIMARY_KEY */
		public Nullable<DateTime> @MaxModificationTimestamp
		{
			get
			{
				return this.@maxModificationTimestamp;
			}
			set
			{
				this.@maxModificationTimestamp = value;
			}
		}
		
		#endregion
	}
}
